### PR TITLE
fix(client): lint issues for confirm() messages not referencing the `window` object

### PR DESCRIPTION
**Pull request by lirantal**

### CODE REVIEW

**Comment by mleanos** [comment]
Could we use Angular's `$window` service instead? I think we're trying to move in that direction with $window, & $document. I mentioned it here https://github.com/meanjs/mean/pull/1202#discussion-diff-54761229

**Comment by lirantal** [comment]
@mleanos you're right, I updated accordingly.

**Comment by ilanbiala** [comment]
LGTM

**Comment by mleanos** [comment]
I just double checked, and the ESLint warnings go away after the changes here are implemented.

**Pull request merged**
