### PR TITLE
fix(Travis build): PhantomJS and SocketIO dependencies

### PR DESCRIPTION
**Pull request by trainerbill**
changed PhantomJS and SocketIO dependencies to ~ to stop breaking changes.

### CODE REVIEW

**Comment by codydaig** [comment]
LGTM

**Comment by ilanbiala** [comment]
LGTM, not sure why those were not using `~` before.

**Comment by codydaig** [comment]
@ilanbiala There seems to be a bunch that were/are like that. These in particular were breaking things so we fixed rapidly.

**Comment by trainerbill** [comment]
Yeah, someone should probably do a dependency audit.  I can't think of any reason why they wouldnt all be ~.  Any breaking changes, ie minor/major upgrades, should be tested before.

**Pull request merged**
