### PR TITLE
fix(core): Remove the <base> tag (continues #1230)

### LINKED ISSUE #1224: <base href="/"> breaks SVG IRIs and element CSS URLs
Unfortunately, the `<base href="/">` tag in `modules/core/server/views/layout.server.view.html` breaks SVG IRIs and element CSS URLs.

For those very reasonably unsure what I'm referring to:

- [SVG IRIs](https://www.w3.org/TR/SVG/linking.html#IRIandURI) are the formal name for SVG attribute values like `url(#myElement)`, used throughout SVGs for referencing other elements usually defined in `<defs>` tags. They are the only way to do a large number of things in SVGs including filters/manipulations, text paths, marker-start/-mid/-end (the way to make lines into arrows). The [SVG spec 25 different SVG elements](https://www.w3.org/TR/SVG/linking.html#processingIRI) that can use IRIs--many of which only work with IRIs.
- Similarly, element [CSS URLs](https://developer.mozilla.org/en-US/docs/Applying_SVG_effects_to_HTML_content) are commonly used for a number SVG-like effects on regular HTML elements, like `mask`, `clip-path`, and `filter`. These only work with relative URLs.

The problem arises because, as mentioned in [this article](http://webdesign.tutsplus.com/articles/quick-tip-set-relative-urls-with-the-base-tag--cms-21399), `<base href="/">` will apply to *all* URL/IRIs in the document, including SVG IRIs and CSS URLs, which basically always reference a relative element `id` on the same page.

Take [this jsfiddle](https://jsfiddle.net/dofxce2y/). Note the happy little triangle making the `<polyline>` into an arrow. Now look at [the same fiddle with `<base href="/">`](https://jsfiddle.net/dofxce2y/1/). The arrow is no longer there because the IRI is now pointing incorrectly to `https://jsfiddle.net/#Triangle`. You can tell by hovering over the blue-linked `url("#Triangle")` style value in a Chrome style inspector on the `<polyline>`.

Unfortunately, there's only one way to override the `<base>` tag, and it only works in some situations and is pretty unpleasant. [This jsfiddle](https://jsfiddle.net/dofxce2y/6/) demonstrates that you can instead use an absolute URL in the IRI, since `<base>` tags only apply to relative URLs. Unfortunately, this has its downsides:

1. This forces you to add logic in your template to insert the absolute path to the current page into the URL, which is annoying if the URL is dynamic, and frankly, kinda ugly. It's also very fragile, breaking if the page's URL changes, like when you click "Run" on [the same jsfiddle](https://jsfiddle.net/dofxce2y/6/), which just changes the URL. And it only gets more complicated if you have different URLs for the same page (e.g. vanity URLs).
2. This workaround doesn't work at all if you don't have the ability to insert the absolute path into the SVG IRI or CSS URL (perhaps they are generated by a third-party library, or are simply third-party content in the case of SVG artwork).
4. This workaround also doesn't work at all if you have multiple elements with the same `id` in separate `<svg>` elements on the same page and want to refer to them. For example, there is simply no way to make [this jsfiddle](https://jsfiddle.net/dofxce2y/4/) work with a `<base>` tag and absolute URLs, although it's clearly a valid use (since `<svg>` elements kind of have their own documents, so the two `id`s aren't actually colliding).

So what can we do? Well, in [this StackOverflow question](http://stackoverflow.com/questions/12303241/how-to-override-base-tag-without-removing-the-tag-itself), a user asks how to override `<base>`, to which one user responded (back in *2012*):

> The `base` tag is normally not needed these days. It is better to use server-side technologies that let you construct addresses from one or more base addresses. So quite possibly the best approach is to get rid of the tag.

It took me a good 30 mins of probing to get to the bottom of this, and I'd consider myself an expert with JS/HTML/CSS. For less experienced engineers, this could be a real tough bug to track down. And with the rise of visualization libraries like D3, SVG bugs like this are only going to come up more and more often. Since all of the page resources are controlled by a server-side template anyway, I think we should strongly consider prioritizing correctness over convenience and remove the `<base>` tag entirely, switching to fully-qualified path names for external resources.

Sorry for the essay :sweat_smile: Thoughts?

### PR DESCRIPTION
**Pull request by mleanos**
@0x24a537r9
>Fixes #1224. Everything looks good in the browser and server/e2e tests, but unfortunately the unit tests are broken, and I'll probably need some guidance from someone more familiar with Angular/Karma.

This is a continuation of #1230, in an attempt to finalize the changes by fixing the broken tests.

NOTE: The fixes to the client-side tests aren't ideal. At the moment, they will suffice. [This comment](https://github.com/angular-ui/ui-router/issues/212#issuecomment-60803437),
among others in that issue, led me to choose this method as the fix to
avoid having to change any core code.

### CODE REVIEW

**Comment by lirantal** [comment]
@mleanos thanks.

**Comment by mleanos** [comment]
@lirantal Yes. We can close to the other.

**Comment by lirantal** [comment]
Ok I'll close the older one. Can you rebase your branch here with the latest changes?

**Comment by mleanos** [comment]
I'm waiting for #1547 & #1532 to be merged, before I rebase. Those PR's should go in first, and will cause conflicts with this. I'll fix as soon as they go in.

**Comment by mleanos** [comment]
@lirantal This has been rebased.

**Comment by lirantal** [comment]
It's a big change through a lot of files so I want to test it a bit locally to confirm it's ok not breaking anything first and then I'll merge.

**Comment by mleanos** [comment]
Also, when you merge, don't squash. I noticed with the other PR that I took over, the commits from the original contributor were squashed into mine; thus, the original author's commits aren't reflected in the history.

If you'd prefer, I can squash my commits down to 1 so there would be only two going in with this merge. Either way, it's not a big deal to me but we should try to at least keep @0x24a537r9's commits.

**Comment by lirantal** [comment]
Of course, no problems.

**Comment by lirantal** [comment]
Seems to work great, thanks @mleanos and @0x24a537r9 for all the help!

**Comment by abumere** [comment]
Looks like removing the <base> tag also broke the ability to add a URL in the config/assets/default or production files. 

Normally you could add a URL as a css dependency (lets say to a google font) but now it appends localhost to the beginning of the URL

**Pull request merged**
