### PR TITLE
[bug] Missing owasp dependency

### PR DESCRIPTION
**Pull request by mleanos**
This adds the missing owasp-password-strength-test front-end package to
config/assets/production

### CODE REVIEW

**Comment by codydaig** [comment]
@mleanos It is here, is it not? 
https://github.com/meanjs/mean/blob/master/bower.json#L16

**Comment by jloveland** [comment]
This is already provided by `config/master/assets/default.js`:
https://github.com/meanjs/mean/blob/master/config/assets/default.js#L19

Only if owasp-password-strength-test had a minified lib, we would add it to the production.js right?

**Comment by codydaig** [comment]
Sorry. I was looking at the wrong file. @mleanos is correct. The arrays don't merge in the config. So, for it to be included in the production environment, it must be listed in the production env file. 

LGTM

**Comment by ilanbiala** [comment]
@codydaig @jloveland @mleanos can we get #907 and #909 in one PR because they both really have to do with the same thing and it will keep the commit history cleaner.

**Comment by codydaig** [comment]
@ilanbiala Combined in #909.

**Comment by mleanos** [comment]
@ilanbiala Yea, I'm fine with this being combined to #909

**Comment by mleanos** [comment]
@ilanbiala @codydaig Thanks. Didn't see this was closed, before my last comment.

**Pull request closed without merging**
