### PR TITLE
MEAN.JS 0.6.0

### PR DESCRIPTION
**Pull request by lirantal**

### CODE REVIEW

**Comment by simison** [comment]
Update also [package-lock.json](https://github.com/meanjs/mean/blob/master/package-lock.json#L3)

**Comment by simison** [comment]
Suuuper. :-) 🌮 👍 :tada:

**Comment by Ghalleb** [comment]
Will you add #1857 and #1854 in version 0.6.0?

**Comment by lirantal** [comment]
I didn't follow those PRs but if @mleanos and @simison can help get them through I don't mind waiting a few extra days to include them.

**Comment by mleanos** [comment]
@lirantal #1857 is in, and we're just waiting for a rebase & commit message changes for #1854.

**Comment by mleanos** [comment]
#1564 Has been merged as well, and probably should be included in this release.

**Comment by lirantal** [comment]
@mleanos great, I'll wait for #1854 and will update the releases notes + merge this in.

**Comment by Ghalleb** [comment]
@lirantal 
I fixed the conflicts in #1854

**Comment by mleanos** [comment]
Just merged #1854.

@lirantal Thanks for waiting :)

**Comment by lirantal** [comment]
@simison @mleanos I updated package.json, package-lock.json and CHANGELOG with latest master. Please review and let me know if we missed anything.

**Comment by mleanos** [comment]
FYI, just one job of the build failed with a `ECONNRESET` error. So we're good here. I'm going to re-run the job just for prosperity 😸

**Comment by lirantal** [comment]
👍

**Pull request merged**
