### PR TITLE
PayPal Authentication

### PR DESCRIPTION
**Pull request by trainerbill**
New PR for PayPal Authentication

### CODE REVIEW

**Comment by trainerbill** [comment]
@ilanbiala Can we get this merged?  Let me know if you want anything else.

**Comment by ilanbiala** [comment]
@trainerbill is this the same as #545, just rebased? The PR should be against 0.4.0 though.

**Comment by trainerbill** [comment]
@ilanbiala Yes this is the same just rebased.  Do you need me to do anything for it to go to 0.4.0?

**Comment by lirantal** [comment]
@trainerbill you need to close this PR and locally switch to 0.4 branch, and branch out of that with the PayPal authentication feature and submit that as a PR.

**Comment by trainerbill** [comment]
@lirantal You can close this PR.  I created a new one on the 0.4.0 branch here:

https://github.com/meanjs/mean/pull/610

Really like the changes in 0.4.0 by the way.  When is the official release?

**Comment by lirantal** [comment]
It's coming closer than you think :)
We're finalizing stuff there and then we look at all the outstanding 0.4 PRs and consider merging them.

Thanks!

**Comment by trainerbill** [comment]
I closed this as the follow PR should be used for 0.4.0

https://github.com/meanjs/mean/pull/610

**Pull request closed without merging**
