### PR TITLE
fix(docs): Fix comments content and style

### PR DESCRIPTION
**Pull request by combefis**
Changed some bad comments referencing the Articles module in other modules.
Typo fixed in xxx.client.modules.js files ("Application" => "Applicaion")
Full stop character removed at the end of line comments

### CODE REVIEW

**Comment by mleanos** [comment]
LGTM. Thanks.

**Comment by codydaig** [comment]
@combefis I like the PR and thank-you for the contribution! However, I would like to hold off on this PR until after the style guide refactor. I don't want to make the larger more complex PRs rebase for typos. I'd rather you rebase this after that gets merged.

**Comment by combefis** [comment]
@codydaig that's OK to me, I'll wait until the style guide refactoring is complete, and then rebase this PR. Thanks!

**Comment by codydaig** [comment]
@combefis The PR has been merged. Go ahead and rebase here. If the rebase is just too messy, feel free to open a new PR as well!

**Comment by combefis** [comment]
Done!

**Comment by codydaig** [comment]
LGTM

**Comment by ilanbiala** [comment]
LGTM.

**Comment by mleanos** [comment]
What about `fix(grammar)`?

`fix(docs)` might be confusing, as it conveys that documentation has been changed, when looking back at the change log. Technically inline comments were changed, not documentation. Just a thought :)

**Comment by ilanbiala** [comment]
I'm trying to generalize because it's fixing comments for documentation. Grammar also isn't really something we've ever used, and I don't want the changelog to just have 1 line under that.

**Comment by mleanos** [comment]
You're exactly right. Inline comments is a form of documentation. Carry on :)

**Comment by combefis** [comment]
@ilanbiala I just edited the commit message!

**Pull request merged**
