### PR TITLE
Admin users require role

### PR DESCRIPTION
**Pull request by mleanos**
These changes make the role field required in the User model. Changes to
the Admin user edit view were added to provide validation for the role
field.

As an added enhancement, the user's roles are displayed in the Admin
user list view.

Added model tests to accommodate these changes.

### CODE REVIEW

**Comment by codydaig** [comment]
LGTM

**Comment by lirantal** [comment]
Looks good. I want to merge my additions to the user model tests for and then you can probably rebase again for the conflicts

**Comment by mleanos** [comment]
@lirantal Sounds like a plan. I figured I would just adjust the tests according to your changes. Once you merge, I'll rebase and update these new tests. Thanks.

**Comment by lirantal** [comment]
Looks like we're good here to merge.

**Pull request merged**
