### PR TITLE
fix(core): Add "additionalProvidersData" to "safeUserObject"

### PR DESCRIPTION
**Pull request by francisdaigle**
Needed for management of social accounts.

### CODE REVIEW

**Comment by mleanos** [comment]
LGTM. I've tested this, and verify that the social accounts are now showing up correctly.

Thanks @francisdaigle!

**Comment by codydaig** [comment]
@mleanos @francisdaigle Was this a bug? Can someone elaborate slightly more on why this was needed? I don't have an issue with it, just want to vet it before it gets merged. Thanks!!!

**Comment by mleanos** [comment]
@codydaig I hadn't noticed before, but on the latest *master* the social accounts profile view wasn't showing the connected accounts. This is because the `additionalProvidersData` field isn't present on the client-side User object. 

In short, it is a bug that this is fixing.

**Comment by francisdaigle** [comment]
@codydaig: Yep. Came across it while working on our fork. Must have been omitted by mistake. Makes it a fix I would think for the reasons @mleanos cited.

**Comment by codydaig** [comment]
Thanks @mleanos and @francisdaigle for the clarification.

**Pull request merged**
