### PR TITLE
Improve Heroku deployment documentation

### PR DESCRIPTION
**Pull request by ChrisMaher**
Ive noticed that if i add an env variable to Heroku 

**NODE_ENV production **

after running 

**grunt build**

It then uses the concatenated application.js files which makes my website load in about 1/5th of the time hosted on Heroku. Ive seen some people around github complaining about slow loading MEAN.js projects and no mention of this.

Ive also noticed people complain about a white page when they deploy to Heroku and this is the same solution. **grunt build** then set the Variable **NODE_ENV production ** in Heroku

I would say it would wise to add this in the documents somewhere relating to Heroku deployment.

Also this is my first pull request so apologies if im doing something wrong.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@ChrisMaher something went wrong here.

**Comment by codydaig** [comment]
@ChrisMaher Howdy! So, it looks like your using code from the master branch but are attempting to make a PR against 0.4.x. If you're trying to update documentation in 0.4.x I would update it on the website repo meanjs/meanjs.github.io Otherwise, submit the PR against the master branch!

**Comment by ilanbiala** [comment]
@ChrisMaher did you see what @codydaig said?

**Comment by codydaig** [comment]
@ChrisMaher Seeing no response, I'm closing this PR.

**Pull request closed without merging**
