### PR TITLE
Database seeding

### PR DESCRIPTION
**Pull request by trainerbill**
New PR for:

https://github.com/meanjs/mean/pull/785

### CODE REVIEW

**Comment by trainerbill** [comment]
Before @ilanbiala asks whats up with package.json....  For some reason my npm --save alphabetizes but I don't see that as a bad thing...  the only thing this adds is crypto.

**Comment by lirantal** [comment]
Cool, thanks @trainerbill - I like it.

**Comment by mleanos** [comment]
Thanks @trainerbill this looks good.

**Comment by trainerbill** [comment]
Awesome.  @codydaig I think we should document this on the README and any other documentation we have... 

Development will seed admin and user everytime.  Just grab the pass out of the console
```js
MONGO_SEED=true grunt
```

Production:
```js
MONGO_SEED=true grunt prod
```

Will seed the admin user one time if it does not already exist.  You have to copy the password and save it.

**Pull request merged**
