### PR TITLE
Revert "Enhancement(core):Relative position attribute added to the header."

### PR DESCRIPTION
**Pull request by trendzetter**
Reverts meanjs/mean#1276

### CODE REVIEW

**Comment by trendzetter** [comment]
Use standard bootstrap classes instead to fix the issue #1275

**Comment by ilanbiala** [comment]
@generalgmt @d3dc does this fix work for you?

**Comment by trendzetter** [comment]
@ilanbiala He did confirm: https://github.com/meanjs/mean/issues/1275#issuecomment-211316609

**Comment by ilanbiala** [comment]
@generalgmt said navbar-static-top, did he mean navbar-fixed-top?

**Comment by trendzetter** [comment]
@ilanbiala navbar-fixed-top is what is used now in meanjs now. What the commit did is override the bootstrap class with some custom css. The proper fix for his issue is replacing navbar-fixed-top with navbar-static-top in his project.

**Comment by ilanbiala** [comment]
@codydaig @mleanos any issues with this?

**Comment by mleanos** [comment]
I agree with @trendzetter here. We definitely should be using the standard bootstrap class.

I'm fine with this revert. Thanks @trendzetter.

**Pull request merged**
