### PR TITLE
Improvements on configurablity

### PR DESCRIPTION
**Pull request by hawmen**

### CODE REVIEW

**Comment by lirantal** [comment]
Merge issues here... also this should probably be done on 0.4 branch

**Comment by codydaig** [comment]
@lirantal Is this still something we want to implement into 0.4.0 or Can this pull request be closed?

**Comment by codydaig** [comment]
#446

**Comment by lirantal** [comment]
overall the PR looks valid but this should go into 0.4.0

**Comment by codydaig** [comment]
Since this sat untouched for a couple months, I submitted pull request #664 

However, this only covers the server side aspects of the configuration changes. I'm not as fluent in the angular side of things, so I have not have those changes.

**Comment by lirantal** [comment]
closing this due to #664

**Pull request closed without merging**
