### PR TITLE
Remove targets on signin and signup anchors

### PR DESCRIPTION
**Pull request by cdriscol**
Removing target on signin and signup anchors to prevent a complete page reload when changing to those states.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@cdriscol can you provide a source for what this fixes in Angular/in general?

**Comment by cdriscol** [comment]
@ilanbiala, I noticed that on the header the signin and signup were causing page refreshes because they were using a target="_self".  Since those links just change state using data-ui-sref, they do not need to cause this page reload.

I looked at meanjs/master branch - and the behavior there is to change state and not reload.  So I'm not sure how/why the target's were added in 0.4.0 - but they're not needed (from what I can tell) and it negatively impacts the user experience by causing a page reload rather than a smooth state transition to the signin/signup partials.

**Comment by cdriscol** [comment]
@ilanbiala, I should also note that I was going to create an issue for this, and still can, if that's what we should be doing.  With the size of this change, I wasn't sure if creating the issue was just extra overhead..

**Comment by lirantal** [comment]
@ilanbiala  if @cdriscol can confirm that this doesn't break anything then I see no harm in merging. what do you think?
@cdriscol I assume you can run some tests locally and confirm please?

**Comment by cdriscol** [comment]
@lirantal, everything works as expected after this change.

**Comment by lirantal** [comment]
@ilanbiala LGTY?

**Comment by ilanbiala** [comment]
Yep, you can merge.

**Pull request merged**
