### PR TITLE
Update users.profile.server.controller.js

### PR DESCRIPTION
**Pull request by Edo78**
null isn't a valid json

### CODE REVIEW

**Comment by Edo78** [comment]
@roieki "fail" usually doesn't mean "beaks everythin", errors and exceptions are manageable (think about the whole set of error code 4xx and 5xx) ...

@ilanbiala I'm sorry but I don't understand what you mean ... where do you want to put the check ?

**Comment by roieki** [comment]
@Edo78 - I actually think it *should* break everything if a user isn't loaded... Either way, it makes little difference - you have to check whether or not you have a user loaded or not.

**Comment by Edo78** [comment]
@roieki every API should return something valid even if it's called with parameters full of garbage.
The more I think about this PR the more I'm willing to change adding even an error code like 404
Returnig something invalid let the client wonder if the fault it's on itself or on the server side ...

**Comment by ilanbiala** [comment]
@Edo78 on the client side (Angular) you have to check against `{}` (truthy) instead of `null` (falsy), which changes lots of things.

**Comment by ilanbiala** [comment]
@Edo78 you'll also have to fix the commit message if we get everything changed accordingly and everyone thinks this is a good idea to merge.

**Comment by ilanbiala** [comment]
@NeverOddOrEven do you mean `req.user = user;`? The other big comparison issue is in all the Angular code @Edo78 which like I said before:
> you have to check against {} (truthy) instead of null (falsy), which changes lots of things.

**Comment by Edo78** [comment]
I'm sorry, this is my first PR on github and I'm not a mean.js expert so maybe I'm screwing something but I can't event find where in the frontend is called this code ...

**Comment by lirantal** [comment]
@Edo78 would you like to re-consider this PR for 0.4.0?
@ilanbiala I think Edo has a good point in APIs returning an empty object (or error object) rather than null.

**Comment by ilanbiala** [comment]
@lirantal I agreed before, but it has to be fixed on the frontend as well.

**Comment by lirantal** [comment]
@ilanbiala actually, taking another look here this whole discussion is futile because I couldn't find any use in the route /api/users/me so maybe we just need to remove it as it's obsolete.

Can you confirm?

**Comment by ilanbiala** [comment]
Yeah I'm not finding a use. Do you remember us using this at any point?

**Comment by lirantal** [comment]
Yes, it's used in master AFAIR.
Ok well, I'll go ahead and remove it.

**Comment by ilanbiala** [comment]
@lirantal we can close this then, right?

**Comment by lirantal** [comment]
yeah, closing, thanks.

**Pull request closed without merging**
