### PR TITLE
fix(wiredep): directly wire html source [WIP]

### PR DESCRIPTION
**Pull request by shanavas786**
Wiring html source directly doesn't fix issue #1360 completely as [karma.conf.js](https://github.com/meanjs/mean/blob/master/karma.conf.js#L42) still relies on it.

It also can be (and has to be) wired using wiredep, but the lint issue of wiring array arises there.

Any thoughts ?

### CODE REVIEW

**Comment by lirantal** [comment]
@shanavas786 status on this one?

**Comment by shanavas786** [comment]
@lirantal I think it is done :). All tests passed. Please review

**Comment by shanavas786** [comment]
Travis build failed. But no errors locally.
It is `Article CRUD` tests which fails and I believe this PR doesn't touch anything related to it.

**Comment by codydaig** [comment]
I don't like the idea of keeping track of the dependencies in multiple places. The solution we had before only required you to update one spot and it propagated to the remainder of the files.

**Comment by shanavas786** [comment]
@codydaig the earlier approach was keeping dependencies in `default.js and production.js`. Here we directly keep the dependencies at the actual destinations `layout.server.view.html and karma.conf.js`.

**Comment by ilanbiala** [comment]
@lirantal status of this PR?

**Comment by lirantal** [comment]
@shanavas786 I agree with @codydaig, something just doesn't feel right to take the dependencies out of the configs and put them in karma or directly in the layout.
Can you please review this again?

**Comment by simison** [comment]
Sorry but -1 also from here. This seems hacky. Rather would put efforts towards #1087

**Comment by lirantal** [comment]
Indeed, let's close.
@shanavas786 Thanks so much for offering to help. See if you can maybe chime in on one of the other open PRs / issues reported.

**Pull request closed without merging**
