### PR TITLE
Mocha test timeouts [fixes #955]

### LINKED ISSUE #955: Mocha intermittent timeouts
We seem to be having intermittent issues with the Mocha tests timing out; including the Travis CI builds failing due to these timeouts. This has been disrupting the flow of contributions with our PR's builds failing. Personally, when I've committed changes to a PR, I have been crossing my fingers that no tests timeout. 

I suggest to implement suite level timeout increases; described here http://mochajs.org/#timeouts. This could be a permanent or temporary solution. Either way, it may save us a lot of headache when running through the CI builds.

I have a branch that I've been testing this with, and it seems to have solved the issue with timeouts. I'm setting the timeout using `this.timeout(10000);` for each server test suite (just once per file). It's a small change to each server test file. 

I wanted to open the discussion before I submitted a PR. Perhaps there is a bigger issue at play here, rather than just latency issues. Any thoughts, or concerns over this approach?

@lirantal @ilanbiala @codydaig @rhutchison @trainerbill @simison @bastianwegge @jloveland

### PR DESCRIPTION
**Pull request by mleanos**
Added a timeout of 10000 ms to each server test file. This is an attempt
to solve the timeout issues that we're experiencing with the Mocha
tests. Especially, this is hoping to address the build fails that are
caused by such timeouts.

Issue is described in https://github.com/meanjs/mean/issues/955

### CODE REVIEW

**Comment by mleanos** [comment]
@lirantal That's unfortunate :( The build didn't fail due to test timeouts. It was caused by "network connectivity" though. 

And chance of re-running the build?

**Comment by codydaig** [comment]
@mleanos You can close and reopen the PR to force Travis to rerun.

**Comment by codydaig** [comment]
@mleanos Also, that could indicate that the timeout was due to network connectivity issues and an issue with Travis, not with our code.

**Comment by mleanos** [comment]
@lirantal @ilanbiala Any thoughts on fast tracking this one? I really think it's gonna help out with all the build fails we're having.

**Comment by lirantal** [comment]
@mleanos I'm ok, but let's see if we get some better ideas from @bastianwegge or anyone else on how to deal with it.

**Comment by lirantal** [comment]
BTW looks like other projects are using similar method (namely meanio, and mongoose https://github.com/Automattic/mongoose/search?utf8=%E2%9C%93&q=%22this.timeout%22&type=Code)

**Comment by mleanos** [comment]
@lirantal Fair enough. And yea, it seems like a straight forward method. Especially, since we can't predict the environmental factors that might contribute to these issues.

I'm definitely curious to understand what @bastianwegge had in mind though.

**Comment by bastianwegge** [comment]
I investigated into the last failing builds on travis and found out that the `node-pre-gyp` ist mostly the reason for the build to fail, when it's trying to rebuild node.

Would you point me to any failing build you're according to? Since I can't reproduce it neither on my local jenkins nor on travis.

Is this a point where mongoose is sometimes taking longer?

**Comment by mleanos** [comment]
@bastianwegge We've been having trouble with the Travis CI builds when submitting, or committing to, a PR. More often than not the issue seems that the test is taking longer than 2000ms, as indicated on the Travis logs. 

There may be other issues that are causing a periodic build fail, but mostly they've been the timeout errors, on any given test. There doesn't seem to be a pattern with which tests fail.

**Comment by bastianwegge** [comment]
Ok maybe I'm missing out on something. The idea of "let's raise the timeout" didn't look good to me at first.

**Comment by mleanos** [comment]
As @lirantal pointed out, it seems that others are using the timeout increase as a method to combat these Travis issues. It's been very frustrating to have the builds fail for no apparent reason, other than a test timeout. So I think this may be a fine solution for now. Perhaps, it's something on Travis' side.

**Comment by lirantal** [comment]
@bastianwegge the timeouts aren't related to node build, they are happening as part of our tests suite when it runs. Some of them are related to interacting with the server API and others are related to database operations

**Comment by bastianwegge** [comment]
@lirantal the timeouts michael is having locally are due to his connection from the local machine to mongolab. He's doing it right testing against a service instead of a local database to avoid issues in that case and he convinced me that it makes sense to set up a higher timeout. We never ran into such issues since our Jenkins has a mongodb locally installed that gets cleared before every run. Do you know what database travis uses?

**Comment by lirantal** [comment]
@bastianwegge we got those timeouts as well on Travis, and I personally also getting them from time to time with a local mongodb installed here

**Comment by codydaig** [comment]
@bastianwegge I believe travis is using a local mongo instance inside the container that the tests are ran in.

**Comment by bastianwegge** [comment]
Yeah, seems to be just fine if nobody's concerned, I just wanted to jump to make you think about it. Go ahead and merge it, let's see if this breakes down the whole "timout" discussion. Otherwise I'd love to investigate with you into it ! :+1:

**Comment by lirantal** [comment]
Cool.

**Pull request merged**
