### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ilanbiala**
This is a WIP PR.

### CODE REVIEW

**Comment by simison** [comment]
@ilanbiala have you looked into [PM2](https://github.com/Unitech/pm2)?

https://www.reddit.com/r/node/comments/2dwsee/forever_vs_pm2/cjuixsb

**Comment by ilanbiala** [comment]
@simison I don't really see any major benefits over forever.

**Comment by codydaig** [comment]
@simison Unitech doesn't credit their contributors anymore, so I prefer not to support a project that doesn't give credit to the authors.

**Comment by lirantal** [comment]
we're using PM2 at work as well.

**Comment by ilanbiala** [comment]
@lirantal Node 0.12 only has failing tests. However, I'd prefer to wait for us to up the test coverage before finalizing this because then we'll have to do less testing before merging.

**Comment by lirantal** [comment]
Cool, fine by me.

**Comment by ilanbiala** [comment]
Not a great idea to do this at once, so I'm closing and we'll do it incrementally as much as we can.

**Pull request closed without merging**
