### PR TITLE
Add comment to remind change for mongo replicaset connection (clean branch source)

### PR DESCRIPTION
**Pull request by PierreBrisorgueil**
Just add a quick comment, in order to remind to update configuration file if you try to connect your production to a cluster of mongo server.

server: { ssl: true, sslValidate: false, ....

must be

replset: { ssl: true, sslValidate: false, ....

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks @PierreBrisorgueil, I left a small comment if you can fix it I'll merge the PR.

**Comment by PierreBrisorgueil** [comment]
done, don't find how you configure your beautify :p 
my javascript beautify add this indentation automatically

**Comment by mleanos** [comment]
LGTM.

@lirantal I restarted the build, as I think changes you made recently have fixed the problem with Travis builds. If it passes, this should be ready.

**Comment by mleanos** [comment]
@lirantal The build is still failing. I think this change can be merged in regardless. Otherwise, we'd have to ask Pierre to rebase, but that seems unnecessary to me.

**Comment by lirantal** [comment]
Agree, it's a comment change and we can definitely push, thanks @mleanos for triaging it.

**Pull request merged**
