### PR TITLE
Global Mocha timeout

### PR DESCRIPTION
**Pull request by mleanos**
Added the timeout option to the Mocha grunt task; set to 10000.

Removed the individual test suite timeouts, for all server tests.

As discussed in #964

### CODE REVIEW

**Comment by ilanbiala** [comment]
@mleanos just merge the Grunt and Gulp PRs together.

**Comment by mleanos** [comment]
@ilanbiala Ok, will do. I just thought we were keeping Grunt & Gulp separate since we're not *officially* supporting Gulp.

**Comment by mleanos** [comment]
@ilanbiala Combined the Gulp change into this PR.

**Comment by vaucouleur** [comment]
LGTM (grunt & gulp test-ed). Thanks.

**Comment by lirantal** [comment]
@ilanbiala I think we can add it as part of 0.4.2, you have any objections?

**Comment by ilanbiala** [comment]
LGTM. :+1:

**Comment by codydaig** [comment]
LGTM

**Comment by mleanos** [comment]
Thank you @lirantal 

@vaucouleur Thanks for the suggestion.

**Pull request merged**
