### PR TITLE
Fix npm warnings

### LINKED ISSUE #1015: problems on nodejs v4.2.1 LTS.
Have problems with karma on ```npm install``` with nodejs v4.1.2 : 

```
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.1.2","npm":"2.14.4"})
npm WARN peerDependencies The peer dependency istanbul@0.x.x included from grunt-mocha-istanbul will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

### PR DESCRIPTION
**Pull request by ilanbiala**
Fixes #1015

### CODE REVIEW

**Comment by codydaig** [comment]
@ilanbiala This is failing on Node 0.10.

**Comment by ilanbiala** [comment]
So it turns out that to upgrade to Karma 0.13, we can no longer use npm 1.4.28 because the way it handles peerDeps is different and https://travis-ci.org/meanjs/mean/jobs/88529913#L429 these errors are because of the old semver used I believe. In any case, @lirantal @codydaig @mleanos @jloveland what do you guys think about this? Eventually we'll want to update Karma, and I think we can just ask people to use npm >=2 in engines, right? We can make this change in 0.5.0 if you guys agree. I'm open to other suggestions too.

**Comment by codydaig** [comment]
@ilanbiala I'm all for dropping 0.10 support in 0.5.x to get this merged in.

**Comment by ilanbiala** [comment]
Yeah, 0.10.0 was released in 2013, and 0.12 has been around and io.js and Node 4, so I think most of the people have moved to Node 0.12 if not higher.

**Comment by codydaig** [comment]
Unless @lirantal has any objections too this, once 0.4.2 is released, we can remove 0.10 from the travis builds.

**Comment by lirantal** [comment]
I'm ok.

**Comment by codydaig** [comment]
@ilanbiala Can you update the commit message and rebase? I think this is ready os go.

**Comment by ilanbiala** [comment]
@codydaig some weird stuff happened in the rebase. I think I'm just going to create a new PR.

**Comment by codydaig** [comment]
No worries. It happens.

**Pull request closed without merging**
