### PR TITLE
Bumping to version 0.5.0

### PR DESCRIPTION
**Pull request by lirantal**

### CODE REVIEW

**Comment by simison** [comment]
Don't forget https://github.com/meanjs/mean/blob/master/CHANGELOG.md

**Comment by lirantal** [comment]
Of course, I was just now installing the conventional-changelog npm lib :)

**Comment by lirantal** [comment]
Also tagged: https://github.com/meanjs/mean/releases/tag/0.5.0

**Comment by codydaig** [comment]
WooHoo!

**Pull request merged**
