### PR TITLE
Fix issue #424

### LINKED ISSUE #424: File ignore pattern matches characters, not words
In config/assets/default.js ```module.exports.server.routes```
I'll post a fixing PR soon.

### PR DESCRIPTION
**Pull request by vepasto**
Fixes #424.

### CODE REVIEW

**Comment by ilanbiala** [comment]
What effect does this have?

**Comment by vepasto** [comment]
Because the current code does not allow any modules name to end with letter 'c', 'o', 'r' or 'e'.

**Comment by ilanbiala** [comment]
If it ends in `.routes.js`, this shouldn't be a problem, but if someone changes it then there may be issues. Can you link the docs that show this change is the fix? If everything looks good, I'll merge it in.

**Comment by vepasto** [comment]
Working: http://www.globtester.com/#p=eJzTz81PKc1JLdZX1EjOL0rV1C8uTUrLz0lJLQIAe0UJaA%3D%3D&r=eJyVjssOgjAQRX%2Bl6UoTtVKjtlD6L%2FSBkBSGdIpRv16QDQs3zOIms7j3HOXaJ7GhQixpVyXbUK1wqHqC6R18SWvo0xHbj89JJk%2F8PN%2F9xuVFXodXQSwEiDmJD7MT%2FEAyIaaQYl9QzTpwY%2FDIIDU%2BLg%2FD0dQQnI%2BKzRStTNSKTQ5arUQ2OaxIFuIfxJapxWfp%2FbS%2BHzNb8A%3D%3D&
Not working: http://www.globtester.com/#p=eJzTz81PKc1JLdbXilZMzi9KjdUvLk0CAFGiB30%3D&r=eJyzScksU0jOSSwutlVSstPPzU8pzUkt1k%2FOL0rVLy5NstEHytvZYFeUX5KRWgThYFebm1iSnIFdQzFCBwDsqS8K&

**Comment by ilanbiala** [comment]
LGTM, @lirantal?

**Comment by nanuuki** [comment]
This probably hasn't been noticed since the generator will append an `s` to the end of module names.

**Comment by lirantal** [comment]
yes, that looks alright, we can merge.

**Pull request merged**
