### PR TITLE
feat(yarn) bower to yarn, related to #1909

### PR DESCRIPTION
**Pull request by PierreBrisorgueil**
Begin switch from bower to yarn, related to #1909
Switch done with the [bower-away](https://github.com/sheerun/bower-away)

(& clean some scripts in package.json, maybe some mistake to revert)

### CODE REVIEW

**Comment by lirantal** [comment]
this is really great @PierreBrisorgueil!  🎉 
would you like to finalize the remaining work? (I wasn't sure about what you refer to in the 2nd bullet)

**Comment by PierreBrisorgueil** [comment]
thx, but I deleted my bullets, I was missing a moment on the subject

I think i switch to fast to yarn to test it .. 
https://medium.com/netscape/npm-5-yarn-killer-ba69737b24d0

and I just read that : https://github.com/meanjs/mean/issues/1087

we need to choose between  ( in order to keep public/dist) :

- yarn & symylink between node_module/public & publis/dist 
- or npm Webpack
- or npm Browserify

it think npm Is better, because more used. 

for Webpack or Browserify http://blog.namangoel.com/browserify-vs-webpack-js-drama 

maybe the better choice is Browserify because we are on a simple stack without angular x

**Comment by lirantal** [comment]
In terms of yarn vs npm I'm using yarn everywhere personally but npm is good too.
I'd go with the npm+webpack

**Comment by PierreBrisorgueil** [comment]
ok, thx, i will quickly end this PR, and see after if i have time to test npm+webpack

ok for you ? 


But for the travis log https://travis-ci.org/meanjs/mean/jobs/348762357
it seems like we have another issue relative to https://stackoverflow.com/questions/39541739/chromedriver-error-chrome-version-must-be-52-using-nightwatch

**Comment by PierreBrisorgueil** [comment]
closed to open a new clean PR.

**Pull request closed without merging**
