### PR TITLE
[WIP] User experience improvements on authentication/social profile #153

### PR DESCRIPTION
**Pull request by rhutchison**
This is a WIP - Ref: https://github.com/meanjs/mean/issues/153

### TODO
* Add Toastr messages.
* Redirect to signup with provider data to complete registration.

### CODE REVIEW

**Comment by ilanbiala** [comment]
I like the idea of toast notifications, but that should be in a separate PR.

**Comment by lirantal** [comment]
@rhutchison is this relevant anymore?

**Comment by rhutchison** [comment]
@lirantal I will open a new PR at a later date.

**Comment by lirantal** [comment]
Ok, cool.

**Pull request closed without merging**
