### PR TITLE
Add Deploy to Bluemix button to documentation

### PR DESCRIPTION
**Pull request by ryanjbaxter**
We have already added the Deploy to Bluemix button to the REAME, I am just adding the same button to the CF section of the documentation as well.

@codydaig

### CODE REVIEW

**Comment by ilanbiala** [comment]
Please add the .bluemix folder to gitignore as well.

**Comment by codydaig** [comment]
@ilanbiala I think that the .bluemix folder is required.

**Comment by ilanbiala** [comment]
Oh yeah upon looking at the file it's config and not like a cache or something, never mind.

**Comment by codydaig** [comment]
LGTM

**Comment by ryanjbaxter** [comment]
Yes it is required

-Ryan

**Comment by lirantal** [comment]
@ilanbiala yours to merge...

**Comment by ilanbiala** [comment]
@lirantal tossing into 0.4.1 because it hasn't been released yet.

**Comment by lirantal** [comment]
Great, thanks!

**Pull request merged**
