### PR TITLE
fix(core): Serve static files without session init

### LINKED ISSUE #1089: Serve static files without doing a full session lookup
The session is inited via mongo for ever single static route. This is very inefficient.

### PR DESCRIPTION
**Pull request by pursual**
Fixes #1089

### CODE REVIEW

**Comment by pursual** [comment]
Same as my last PR, hopefully with the correct commit message now.

**Comment by codydaig** [comment]
LGTM

**Comment by ilanbiala** [comment]
LGTM.

**Comment by lirantal** [comment]
LGTM

**Pull request merged**
