### PR TITLE
fix(docs): Add git to Prerequisites

### LINKED ISSUE #1310: Installation Script has errors
Hi, 
I am looking for a good alternative to develop a nodejs app and MEAN.js seem to be a good starting point for me. But when I tried to intall in li,nuz and windows I get Errors and Deprecated packages. These should be updated somehow? The log file is attached.
Thanks,
[npm-debug.log.txt](https://github.com/meanjs/mean/files/217009/npm-debug.log.txt)

### PR DESCRIPTION
**Pull request by simison**
Add git to prerequisites so that especially Windows users would realise to install it.

Fixes #1310

### CODE REVIEW

**Comment by ilanbiala** [comment]
LGTM.

**Comment by mleanos** [comment]
LGTM.

**Comment by codydaig** [comment]
LGTM

**Comment by codydaig** [comment]
@simison Can you also add to the website?

**Comment by simison** [comment]
^ yup!

**Comment by codydaig** [comment]
@ilanbiala I think this can be merged.

**Pull request merged**
