### PR TITLE
Link for download link (NodeJs download)

### PR DESCRIPTION
**Pull request by SibuStephen**
Link for the node js download is mismatching.

### CODE REVIEW

**Comment by lirantal** [comment]
LGTM, thanks @SibuStephen

**Comment by ilanbiala** [comment]
LGTM.

**Comment by codydaig** [comment]
LGTM

@SibuStephen Thanks!

Side Note: Travis has been failing a lot on DB timeouts on this project. Including this PR.

**Comment by SibuStephen** [comment]
@codydaig  should i be raising a new PR then ?

**Comment by ilanbiala** [comment]
Nope, this doesn't affect any code so we can ignore Travis.

**Comment by lirantal** [comment]
Great, thanks @SibuStephen

**Pull request merged**
