### PR TITLE
Fail Build on Node 4.x

### PR DESCRIPTION
**Pull request by codydaig**

### CODE REVIEW

**Comment by lirantal** [comment]
Why? :)

**Comment by codydaig** [comment]
Since it works (and passes) on Node 4.x and the demand is extremely high. I think it keeps the project moving forward, and prevents changes form slipping in that fail on Node 4

**Comment by lirantal** [comment]
It's too soon to officially declare the project is compatible with Node v4.
It was just a few weeks ago where we found ourselves depending on grunt-node-inspector, which by itself, didn't yet update to support Node v4.

Let's give it some time.

**Comment by codydaig** [comment]
Fair.

**Comment by ilanbiala** [comment]
FWIW I'm in support of this.

**Comment by codydaig** [comment]
@ilanbiala @lirantal I'll reopen for discussion.

**Comment by lirantal** [comment]
As far as I care you can keep it reopened until we make v4 support initial,
but I don't think now is the time.

Regards,
Liran Tal.

**Comment by codydaig** [comment]
@lirantal One point that can be made with this is that it would prevent merges from being made that break Node 4 but doesn't mean we officially support Node 4. But, that's the only true point I have to defend this. :-D

**Comment by codydaig** [comment]
@ilanbiala @lirantal I've been using mean with node 4 for several weeks now and haven't encountered any problems (on the master branch) so I'm voting to get this merged to to start supporting it. There's a lot of people that have switched to Node 4 so this keeps the project from breaking on Node 4.

**Comment by ilanbiala** [comment]
:+1:

**Comment by lirantal** [comment]
Cool.

**Pull request merged**
