### PR TITLE
added dependencies to package.json

### PR DESCRIPTION
**Pull request by techunits**
There was few problem in the dependency list in the master branch, now rectified with this commit. Please review.

### CODE REVIEW

**Comment by ilanbiala** [comment]
Can you revert the whitespace changes?

**Comment by techunits** [comment]
Updated the file as per suggestions, please review.

**Comment by ilanbiala** [comment]
@techunits thanks. Which packages specifically did you add to fix the errors? What errors were you facing?

**Comment by techunits** [comment]
"libmime": "~0.1.6"
"hyperquest": "~1.0.1",
"base64-url": "~1.1.0",
"buildmail": "~1.2.0",

Those packages was requested while starting application and was missing from package.json list.

**Comment by ilanbiala** [comment]
@techunits I haven't had to add any of those...and I don't think anyone else has had to.

**Comment by lirantal** [comment]
@techunits as @ilanbiala said, I'm not sure these packages were required. Can you show some output log errors for that? the travis build environment also does npm install IIRC and there weren't any build failures recently due to packages missing

**Comment by lirantal** [comment]
I just did a fresh install of meanjs with the 'master' branch and everything works fine out of the box. @techunits let us know please if you think this is still relevant.

**Comment by techunits** [comment]
Now it seems to be working from after taking checkout from master branch just now. Thanks a lot.

**Pull request closed without merging**
