### PR TITLE
purifycss

### PR DESCRIPTION
**Pull request by codydaig**
Removes excess CSS from the production css. 

Project can be seen here:
https://github.com/purifycss/purifycss

They also have a gulp plugin, just wanted to check too see what people thought before adding gulp as well. 

Brought up a while ago in #221 but I came across this project today and fell in love because it checks the HTML and javascript files. :-D

### CODE REVIEW

**Comment by lirantal** [comment]
I wonder though if there's any risk of false positives and this would result in bad layout due to the relevant CSS being removed?

**Comment by codydaig** [comment]
There's always the chance for that. From what I've heard from people using this in production, it does a great job. However, since there is always the risk I made it so they can still easily use the minified version without any CSS removed here: 'public/dist/application.all.min.css' .

**Comment by simison** [comment]
Is there a way to get this warn about these instead of just bluntly removing stuff? Would be better practise imho.

**Comment by codydaig** [comment]
@simison I made it so running grunt prod does what it always does, but if you want to have purified css, then run grunt prod:pure and it will purify the css. Does that address your concerns?

**Comment by lirantal** [comment]
I prefer having this on 0.4.x so we can test/discuss it further. @ilanbiala ?

**Comment by ilanbiala** [comment]
Yeah 0.4.x please so we can have more time to review.

**Comment by codydaig** [comment]
@lirantal @ilanbiala Sounds good to me!

**Comment by lirantal** [comment]
@codydaig maybe re-submit for master branch now?
also, is there a reason for choosing purifycss over grunt-uncss?

**Comment by codydaig** [comment]
@lirantal I'll have to redo that pull request against master since there's conflicts and I was going to wait until we decided whether or not we actually wanted this feature. 

I picked purifycss because that is what I've used, I'm not opposed to grunt-uncss.

**Comment by codydaig** [comment]
Moving conversation to #221

**Pull request closed without merging**
