### PR TITLE
Updating project dependencies

### PR DESCRIPTION
**Pull request by lirantal**
Updating project dependencies

### CODE REVIEW

**Comment by hyperreality** [comment]
Hi Lirantal, I just fully updated the Helmet and Express config in a new PR #1463

**Comment by lirantal** [comment]
Thanks @hyperreality! Let's hope your build passes :)

**Comment by hyperreality** [comment]
@lirantal yes fingers crossed. I'm not a fan of modules that make tiny changes to configuration variables names after updates!

**Comment by lirantal** [comment]
Closed by merging #1463

**Pull request closed without merging**
