### PR TITLE
[WIP] Update Mongoose

### PR DESCRIPTION
**Pull request by simison**
Just work in progress branch of mine which currently has several things I was testing and learning around updating Mongoose from 4.10 to 4.11. I got the app working, but tests are still failing.

I might get back to this at some point, but meanwhile if anyone else wants to take a stab at updating Mongoose, feel free to look at this.

- Passing user/pass in connection's `options` throws deprecated warning so I removed it, I saw an issue where it was mentioned they might add it back but I lost it. Gotta double check.

- Using [new mongoose connection logic](http://mongoosejs.com/docs/connections.html#use-mongo-client) by setting: `useMongoClient:true`

- Above will make everything into promises so I'm using those in several places instead of callbacks, but I didn't spend too much time in refactoring. I think the whole thing could do with proper rewrite.

- I'm using `mongooseService.loadModels()`'s callback everywhere but this probably isn't needed, I was just trying to get rid of errors with tests.

- Running tests throws "Schema not defined" errors so here are some solutions I was testing

- Rename `mongoose` variables to `mongooseService` so that it's obvious its not referring to mongoose module but our own internal service.

Read more; #1814

### CODE REVIEW

**Comment by mleanos** [comment]
@simison Any particular reason for the other package dependency upgrades in package.json?

I'm planning on spending some time on this, and agree that we could use a re-write of our mongoose service.

**Comment by simison** [comment]
@mleanos nope, I should actually remove that commit from here and open a PR for it.

If you can take over this would be aaaawesome!

**Comment by mleanos** [comment]
> If you can take over this would be aaaawesome!

That was my intention. Do keep an eye on it though. I'll probably need some guidance/review from you at some point 😸

**Comment by simison** [comment]
Sure :thumbsup: just ping me when there's something to check, I'll be busy at a hackathon over the weekend but I can check over something if need.

**Comment by simison** [comment]
Closing as duplicate of #1818

Thanks @mleanos !

**Pull request closed without merging**
