### PR TITLE
fix default session cookie maxAge

### PR DESCRIPTION
**Pull request by pgrodrigues**
Set default session cookie maxAge from 24 minutes to 24 hours.

Sorry @lirantal only noticed now :P

### CODE REVIEW

**Comment by trainerbill** [comment]
Why not set this as a config option?

**Comment by pgrodrigues** [comment]
@trainerbill it is config option.

**Comment by trainerbill** [comment]
haha... I'm being dumb today evidently

**Comment by codydaig** [comment]
LGTM

**Comment by lirantal** [comment]
@pgrodrigues good catch, thanks!

**Pull request merged**
