### PR TITLE
appending a base tag to the head before jasmine tests run.

### LINKED ISSUE #667: adding more client tests causes $location:nobase error
Hey guys -
Anyone know why I'm getting the following error:
```
$ grunt test:client
...
 [$location:nobase] $location in HTML5 mode requires a <base> tag to be present! 
...
````
when I add 2 more client tests?

Adding really simple tests (i.e. below) cause this error.  Doesn't seem to matter what test file I add extra tests to, it always seems to throw this error when I add 2 more tests.  Oddly, if I comment out one of the tests, the error is not thrown.

**chat.client.controller.tests.js**
```javascript
	describe('ChatController', function() {
		it('should pass', function() {
			expect(1).toBe(1);
		});

		it('should also pass', function() {
			expect(1).toBe(1);
		});
	});
```

I can get around the error by not requiring base in $locationProvider.html5Mode

**Line 9 in init.js**
```javascript
$locationProvider.html5Mode({enabled:true, requireBase:false}).hashPrefix('!');
```

But I'm not sure this is a recommended setting for production.

So, anyone have any ideas what's causing this nobase error?  Or does anyone know if using **requireBase:false** is a bad idea for production?

### PR DESCRIPTION
**Pull request by cdriscol**
fixes #667

### CODE REVIEW

**Comment by lirantal** [comment]
@codydaig @mleanos @ilanbiala code review?

**Comment by codydaig** [comment]
LGTM. Doesn't effect the current tests in any way, and all tests pass regardless but I think it's a good addition for any future client side tests.

**Comment by cdriscol** [comment]
Yeah, doesn't really impact anything right now, but I needed it for creating some of [these client tests](https://github.com/cdriscol/mean/tree/client_test_coverage).

**Comment by codydaig** [comment]
@cdriscol Those tests are looking good!

**Comment by lirantal** [comment]
@cdriscol it would be a great addition if you could add client side tests :)

**Comment by cdriscol** [comment]
@lirantal, I plan on adding all my current client side tests and more once I've had some time to refactor a bit.

You can assign #663 to me if you'd like.. I don't think I can assign it to myself..?

**Comment by lirantal** [comment]
@cdriscol sure, let's take it in #663

**Comment by lirantal** [comment]
@cdriscol when linting the code it reports the following issue:
image

Can you advise?

**Comment by lirantal** [comment]
@cdriscol actually when re-running it after an npm install I don't see the problem anymore. I'm not sure if it's something I missed or an actual problem, can you look into it just so we're on the safe side?

**Comment by cdriscol** [comment]
@lirantal - did a clean npm install and jshint passes with no errors.  

I think the only way you'd get that *not defined* error is if your .jshintrc didn't have **"jasmine": true** or if your jshint was out of date (i.e. [before they added jasmine 2.1 globals](https://github.com/jshint/jshint/commit/343c45e990e7f6b93a3374adb3d077894960af01))

**Comment by lirantal** [comment]
@cdriscol got it, thanks. do we have the correct version now on 0.4.0 branch for jasmine on package.json ?

**Comment by cdriscol** [comment]
@lirantal - yeah, all of our current versions should be good in our package.json.

**Pull request merged**
