### PR TITLE
feat(users) Separate admin routes and cleanup

### PR DESCRIPTION
**Pull request by Wuntenn**
- removed unused users.authorization.server.controller
- moved admin routes to their own separate admin path

### CODE REVIEW

**Comment by simison** [comment]
@Wuntenn Could you rebase so that all those other commits wouldn't show up?

**Comment by Wuntenn** [comment]
Hey Simison,

I was hoping they'd not show up or that people would pretend they couldn't see them. I've tried rebasing however I get a load of conflicts.

I've tried a couple times. On my local repo I:
1. `git checkout master`
2. `git pull upstream master`
3. `git rebase upstream master` 

I select the changes visible in the latest code base and reduce all conflicts to zero, then for some reason it gives me an error and says: 
```
rebase in progress; onto e62b680
You are currently rebasing branch 'master' on 'e62b680'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit, working tree clean
```
At that point I'm not sure why I'm getting the errors. It prevents me from progressing via:
4. `git rebase --continue`

**Comment by mleanos** [comment]
@Wuntenn I know I mentioned this in our Gitter discussion, but I wanted to put this here as well..

> I've tried a couple times. On my local repo I:
1. git checkout master
2. git pull upstream master
3. git rebase upstream/master

Try using this as your flow:
1. git checkout master
2. git fetch upstream
3. git rebase upstream/master

Then do development on a new branch for PR's. This will make your merge/rebase life a lot easier.

**Comment by Wuntenn** [comment]
Hey @mleanos, I took @simison's advice from a few months back and created this on a new branch from the outset. I think you nailed the problem though with your advice to `reset --hard`. My master branch somehow was out of sync with meanjs.

Now I forced the changes back up to my remote master. Should work out now (hopefully!)

**Pull request closed without merging**
