### PR TITLE
fix(users): Incorrect UsersService injection

### LINKED ISSUE #1282: Unable to edit profile details
The service for users(UsersService) is being used by the edit profile controller but is named incorrectly.

### PR DESCRIPTION
**Pull request by t-jennings**
Updated edit profile controller to use the users service correctly. Edit profile now working. Closes #1282.

### CODE REVIEW

**Comment by lirantal** [comment]
I can confirm that this is indeed a bug in latest master, thanks @t-jennings

**Comment by mleanos** [comment]
LGTM. Other than the commit message. @t-jennings Could you change it to something like `fix(users): Incorrect UsersService injection`? 

Also, it doesn't look like we have coverage here for the Edit Profile route. Would it be possible to add something to this PR? I'm fine with merging this in as is, since it's a small change & fixes a bug. However, we should start building out our test coverage in these area's.

**Comment by ilanbiala** [comment]
@mleanos it would be nice to get a test for that to increase our coverage.

**Comment by t-jennings** [comment]
Updated title to follow convention. I won't be able to provide a test unfortunately, not familiar enough with testing yet.

This is my first PR so it would be awesome if this got merged.

**Comment by mleanos** [comment]
@t-jennings That's understandable about the test. I think it's ok for this to be merged without an accommodating test. @ilanbiala I'm also not opposed to submitting a test myself to this branch. @t-jennings If I submitted a pull request to this branch, would you be able to merge it in?

Also, we're looking for the actual git commit message to be updated. Not the title of the PR.

**Comment by t-jennings** [comment]
Added commit with correct format for commit message. @mleanos , if you want to submit a PR to add testing I can merge it in.

**Comment by ilanbiala** [comment]
@mleanos adding a test to this via PR sounds good.

**Comment by mleanos** [comment]
@ilanbiala @t-jennings I've submitted a PR to this PR's branch.

Another thing I noticed about the Edit Profile Controller, is that it's injecting the $location service, but not using it. We can probably get rid of it. @t-jennings Could you remove it?

**Comment by ilanbiala** [comment]
Any movement on this?

**Comment by mleanos** [comment]
@ilanbiala @t-jennings We can merge this in as is, and I'll add my test in a separate PR. This is a pretty simple PR, and fixes a bug. So it might be best to just get it merged. WDYT?

See https://github.com/t-jennings/mean/pull/1 for the suggested test coverage.

**Comment by ilanbiala** [comment]
SGTM.

**Pull request merged**
