### PR TITLE
refactor(menus): Refactor to the Menus client service to use functional loops/filters

### PR DESCRIPTION
**Pull request by dalelotts**
The `for loops`, especially the nested `for loops`, over array elements with variable names containing `index` made the code incomprehensible.

### CODE REVIEW

**Comment by dalelotts** [comment]
This also fixes lint errors that appear when upgrading to the latest version of the airbnb eslint configuration - specifically https://github.com/airbnb/javascript#iterators--nope

**Comment by mleanos** [comment]
@dalelotts LGTM. I apologize it took so long to review.

Could you rebase, so the build runs using the current Travis config? If the build passes, I'll merge.

**Comment by mleanos** [comment]
@lirantal I've tested this against the latest *master*, and it's all very straight forward & works. I'd like to merge this soon, which will help in some other refactoring that I'm planning on doing with the Menu service.

I think we can ignore the failing builds. The E2E tests are passing locally, so I think we're safe there.

WDYT? If you're fine with this, then feel free to merge or I can.

**Comment by lirantal** [comment]
sure, go ahead.

**Comment by mleanos** [comment]
Thank you @dalelotts

**Pull request merged**
