### PR TITLE
fix(core): fix page-title directive

### PR DESCRIPTION
**Pull request by itelo**

### CODE REVIEW

**Comment by ilanbiala** [comment]
@itelo can you add some tests so we can catch any other possible issues?

**Comment by mleanos** [comment]
LGTM. +1 on adding some tests.

**Comment by itelo** [comment]
@ilanbiala i don't have much experience creating tests... but i will invest some time on it (:

**Comment by mleanos** [comment]
@itelo What do you think about @trainerbill's comments in #1183?

I like the simplicity of his implementation. I don't quite see his points on your directive being too coupled with the Article's module. However, if that is the case then de-coupling is a good idea.

**Comment by trainerbill** [comment]
@mleanos you linked the wrong PR.

@itelo https://github.com/meanjs/mean/pull/1186

**Comment by mleanos** [comment]
Thank you Andrew. On a train atm, and using my mobile. Not the most efficient combo ;)

**Comment by itelo** [comment]
should I add the test hero or create another PR? And should I put the @trainerbill idea here too?

**Comment by ilanbiala** [comment]
You can add the test here. Also, feel free to give a shot at @trainerbill's idea.

**Comment by codydaig** [comment]
@itelo What's the status of this PR?

**Comment by itelo** [comment]
@codydaig I fix the directive. I started create the test but I'm having some problems with the them...

**Comment by mleanos** [comment]
@itelo Are you still having problems with the tests? If so, hit me up on Gitter & we can work on it together.

**Comment by mleanos** [comment]
@itelo Can you rebase this PR? I spent some time with this PR and incorporated the test you shared with me: https://github.com/itelo/mean/blob/pageTitleTestTask/modules/core/tests/client/page-title.client.directive.tests.js

I had the same problem you described with the Article resolve in the `article.view` route. I'm not quite sure how to solve this problem. I sent you a message on Gitter. Let me know if you'd like to work this together. 

Anyone else have any ideas about the tests for this? @trainerbill ?

**Comment by itelo** [comment]
@mleanos @trainerbill unfortunately i have no time to finished this test, what is the best option?

**Comment by lirantal** [comment]
@mleanos will you please wrap up this PR and merge please?

**Comment by mleanos** [comment]
@lirantal I'll work on getting this PR finalized.

@itelo If I can get a working test implemented for this, I'll submit a PR to your branch. In the meantime, could you rebase this branch from upstream's master?

**Comment by mleanos** [comment]
@lirantal @itelo I'll go ahead and merge this fix as is, and create a separate PR for adding a test.

@itelo Can you rebase this branch?

**Comment by lirantal** [comment]
@mleanos I'm pretty sure you can pull @itelo 's changes, rebase it, and push to a new PR where @itelo 's commits will still be credited when merging this PR. If so, just go ahead and do that.

**Comment by mleanos** [comment]
@lirantal You're right, that would work. I just prefer the original developer to handle these types of things, in case complex conflicts arise. However, in this case the conflict looks to be very simple; I think just the deleted file is causing it.

I was just messaging with @itelo, and I'm going to merge & rebase myself.

**Comment by mleanos** [comment]
@itelo @lirantal 

Closing since #1404 has been merged.

**Pull request closed without merging**
