### PR TITLE
Enable jshint on grunt test tasks

### PR DESCRIPTION
**Pull request by lirantal**
Enabling the lint task when running tests so we can identify coding convention issues on Pull-Requests in the CI

Addresses issue https://github.com/meanjs/mean/pull/645

### CODE REVIEW

**Comment by codydaig** [comment]
LGTM

**Comment by lirantal** [comment]
Thanks, merging.

**Comment by ilanbiala** [comment]
Also #635 no?

**Comment by lirantal** [comment]
Yes, thanks @ilanbiala , it's closed now.

**Pull request merged**
