### PR TITLE
Added imageGaleries

### PR DESCRIPTION
**Pull request by ashokachu12**
## Commit Message Guidelines
```
Header
Blank Line
Body
Blank Line
Footer

The header should look like:
<type>(<scope>): <subject>

The body should have any necessary detailed info about the commit:
An example, references as to where this idea came from, etc.

The footer should have all the issues tagged:
Fixes #123, Fixes #456

So a commit should look like:
feat(users): Add new Yahoo authentication

Yahoo authentication idea proposed by @codydaig
Example implementation in file.js

Fixes #82
```

* Types: 
  * feat - Features, Enhancements, and overall Improvements
  * fix - Fixes, Bugs, HotFixs, etc...
  * doc - Changes to the Documentation and doesn't actually touch any code.
* Scope:
  * The scope should be where the change took place.
  * Examples: users, core, config, articles
* Subject:
  * The subject line should be clear and concise as to what is being accomplished in the commit.
* General Rules:
  * No Line in the Commit message can be longer than 80 characters.
* Reference: [Angular Conventions](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md)

### CODE REVIEW

**Comment by codydaig** [comment]
@ashokachu12 Can you fill in the commit guidelines above and explain why this is needed/wanted, what it bring to the table, etc.... Thanks!!

**Comment by mleanos** [comment]
This seems like an interesting idea. One of the biggest hurdles that I faced with my MEANJS app, was the management of uploaded data (i.e. image, pdf, documents, etc). 

It would be nice to have a foundation for a solution that allows users to upload files to add, edit, and share with others users. I realize that's a tall order, and isn't the aim of this PR. However, it seems to be touching up on the same concept/pattern.

@ashokachu12 I agree with Cody, that we need more details on the relevance of this feature, and the intention. I see there isn't a way for a User to upload these images that the gallery uses. Seems like there might be some other missing parts as well; e.g. the hard-coded list of image-names.

**Comment by codydaig** [comment]
@ashokachu12 Any update on the above asks?

**Comment by codydaig** [comment]
Closing this. @ashokachu12 Feel free to reopen if you want to discuss this more.

**Pull request closed without merging**
