### PR TITLE
Add dockerfile and compose for production

### LINKED ISSUE #1431: MEAN.JS can't set to run in 'PRODUCTION' mode inside Docker
Changed the ENV NODE_ENV to production in the Docker file, before building the image. 

Also tried running container with docker run -e "NODE_ENV=production"-i -t --name www1

Nothing seems to make the MEAN.JS app run in production mode except for grunt prod, which I am not exactly sure how it can be configured to run in the docker container. 

Verified that the NODE_ENV is in fact set to production via: docker exec -it www1 bash printenv command.

### LINKED ISSUE #1435: Add dockerfile and compose for production
- [x] Add Dockerfile for production (#1431)
- [x] Add docker-compose.yml for production
- [x] Update documentation for deployment

### PR DESCRIPTION
**Pull request by FedeG**
feat(deploy) Add dockerfile and compose for production.

Add Dockerfile for production (#1431)
Add docker-compose.yml for production
Update documentation for deployment

Fixes #1435
Fixes #1431

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks @FedeG.
Have you tested both dockerfile and the docker-compose file configuration to work well?

**Comment by lirantal** [comment]
I tested it, seems to be ok including live reload for dev environment.

**Comment by lirantal** [comment]
Actually FYI I tested the dev docker updates, haven't yet tested the production one.

**Comment by lirantal** [comment]
@FedeG can you outline the differences from the dev docker setup? is it just the `NODE_ENV` defaulting to production in the dockerfile?

**Comment by FedeG** [comment]
Differences:
- In Dockerfile:
  + Simplify some commands
  + Add --production to npm install
  + NODE_ENV defaulting to production
  + Remove expose for debug port (remove EXPOSE 5858:5858)
- In docker-compose.yml:
  + Change ports (remove 3000, 5858 and 35729 and add 8443)
  + NODE_ENV defaulting to production
  + Remove code volumes (change ./:/opt/mean.js to /opt/mean.js)
  + Remove expose db port (remove 27017 in mongo container)
- Update documentation for deployment in production

**Comment by lirantal** [comment]
Sounds good.
Thanks @FedeG.

**Pull request merged**
