### PR TITLE
Refresh user providerData when the user log again #511

### PR DESCRIPTION
**Pull request by junit38**
The PR is refreshing the user providerData when the user is loggin again with a social account to maintain the accuracy of the data.

### CODE REVIEW

**Comment by codydaig** [comment]
@junit38 Thanks for the PR! Couple things:
- Please read the contributing doc about the git commit message guidelines: https://github.com/meanjs/mean/blob/master/CONTRIBUTING.md#commit-message-guidelines
- Please update the description to explain what this PR is accomplishing. 
- Please fix the eslint issues outlined in the failed build
- Please ensure that all tests pass. 

Ping me once these are addressed so we can review this PR. Thanks! :-D

**Comment by junit38** [comment]
Ok I fixed the issue but i badly spelled the commit. Is that a problem ?

**Comment by mleanos** [comment]
@junit38 What are your thoughts on just updating the user's Token? 

My idea is that we should treat whatever is in their MEANJS profile, as their *master* profile data. Meaning their data shouldn't be automatically synced with their Provider data. 

In a separate feature PR, we could add a "Sync" button for pulling over their Provider data into their MEANJS profile. But that would require some discussion, and something we can try to add to 0.5.0 as a bonus feature.

**Comment by rhutchison** [comment]
Duplicates #1070 - does this need to remain open?

**Comment by codydaig** [comment]
@junit38 I'm closing this for now. It does seem like a duplicate. Feel free to reopen if it needs to be open. 

@rhutchison Thanks!

**Pull request closed without merging**
