### PR TITLE
Fix npm warnings

### LINKED ISSUE #1015: problems on nodejs v4.2.1 LTS.
Have problems with karma on ```npm install``` with nodejs v4.1.2 : 

```
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.1.2","npm":"2.14.4"})
npm WARN peerDependencies The peer dependency istanbul@0.x.x included from grunt-mocha-istanbul will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

### PR DESCRIPTION
**Pull request by ilanbiala**
Fixes #1015 
Supersedes #1041

### CODE REVIEW

**Comment by codydaig** [comment]
@ilanbiala Don't forget too squash and fix the commit message.

**Comment by ilanbiala** [comment]
@codydaig rebased, if tests pass you can merge whenever you see this if LGTY.

**Comment by codydaig** [comment]
@ilanbiala I'm not trying to nag, but the commit message still needs too be updated to match the new commit message guidelines.

**Comment by ilanbiala** [comment]
@codydaig sorry about that. Is the new message better?

**Comment by codydaig** [comment]
@ilanbiala I just realized that you did update the commit message but just used test instead of fix. Sorry :( I just looked at the PR title and forgot they can actually be different. :( 

LGTM!

**Pull request merged**
