### PR TITLE
fix(core): Remove duplicate angular interceptor

### LINKED ISSUE #1096: Angular interceptor possible dup
Hey, is there any particular reason to have two similar interceptors in [core/services](https://github.com/meanjs/mean/blob/master/modules/core/client/services/interceptors/auth.interceptor.client.service.js) and in [users/config](https://github.com/meanjs/mean/blob/master/modules/users/client/config/users.client.config.js).

IIRC the first one is the most recent and maybe people forgot to delete the latter or merge in the same file possible changes (only one I can think of is `Authentication.user = null;` which is missing in the first one).

### PR DESCRIPTION
**Pull request by pgrodrigues**
Remove the interceptor defined in the users module
Update the interceptor defined in the core module
Update the respective test

Fixes #1096

### CODE REVIEW

**Comment by mleanos** [comment]
LGTM.

**Comment by mleanos** [comment]
@codydaig @lirantal Do we want to leave the file `users.client.config`, as a placeholder, but have it empty? Like what we're doing with *articles.server.config*.

**Comment by pgrodrigues** [comment]
I removed it since there was no js logic to be added to the user config, but I can bring the file back if needed.

**Comment by codydaig** [comment]
@mleanos IMO, placeholder files should be in the generator, not laying around in this repo.

**Comment by ilanbiala** [comment]
No strong feelings about it, so I'd say let's just keep the repo uncluttered.

**Comment by codydaig** [comment]
LGTM

**Comment by rhutchison** [comment]
LGTM

**Comment by codydaig** [comment]
Thanks @pgrodrigues.

Good to see your comments again @rhutchison!

**Pull request merged**
