### PR TITLE
[feat] Purifycss [Fixes #221]

### LINKED ISSUE #221: Suggestion: Removing unused CSS
Hey guys, I was checking out the sample app on Heroku. I ran an audit with the Chrome dev tools. 

image

I was wondering if we can add the [grunt-uncss](https://github.com/addyosmani/grunt-uncss) plugin for removing unused css.

Here's the link to the article - http://addyosmani.com/blog/removing-unused-css/

Cheers,
Shubham

### PR DESCRIPTION
**Pull request by codydaig**
#221

### CODE REVIEW

**Comment by ilanbiala** [comment]
@codydaig since we were planning on switching from Grunt to Gulp (and that is still in flux), I'd rather we focus on that and then add new tasks to whatever build system we decide to move forward with.

**Comment by lirantal** [comment]
@ilanbiala although I'm not sure when are we actually going to move to gulp, and maybe having it in grunt will mean that we can later check what we had in grunt and move it to gulp.

**Comment by codydaig** [comment]
Closing in favor of uncss. Having weird issues with purifycss. Will submit a new PR.

**Comment by lirantal** [comment]
@codydaig you'll test uncss a bit and submit a PR for that?

**Comment by codydaig** [comment]
@lirantal Yup.

**Pull request closed without merging**
