### PR TITLE
Add comment to remind change for mongo replicaset connection

### PR DESCRIPTION
**Pull request by PierreBrisorgueil**
Just add a quick comment, in order to remind to update configuration file if you try to connect your production to a cluster of mongo server.

`
 server: {
         ssl: true,
         sslValidate: false,
         .... 
`

must be 

`
 replset: {
         ssl: true,
         sslValidate: false,
         .... 
`

### CODE REVIEW

**Comment by mleanos** [comment]
@PierreBrisorgueil Can you remove the page-title commit from this PR? I'll give it a review once it has been removed.

**Comment by PierreBrisorgueil** [comment]
ok, sorry, forget it was on my master.

**Comment by simison** [comment]
@PierreBrisorgueil recommend to create a branch and do PR's from there. I think github allows to change PR origin branch from the interface?

**Comment by PierreBrisorgueil** [comment]
@simison hello, yes, my mistake, to quick, to tired. 
Nop, just destination branch i think ... 

we can delete the PR, and i will make a new one if you want.

**Comment by PierreBrisorgueil** [comment]
Closed to clean branch source on my fork.

**Pull request closed without merging**
