### PR TITLE
Removed sudo from npm install grunt

### PR DESCRIPTION
**Pull request by kfuchs**

### CODE REVIEW

**Comment by ilanbiala** [comment]
@roieki @lirantal Why don't we just make the change directly and refer to this PR? I'll do it if that sounds good to you guys.

**Comment by ilanbiala** [comment]
@NeverOddOrEven that's what I thought (especially because of the switch user security issue). @lirantal @roieki can you find any up-to-date source that says it isn't necessary?

**Comment by lirantal** [comment]
definitely npm can, and should probably be globally install-able without requiring sudo.
@simison can you fix the conflicts here so we can merge?

**Comment by simison** [comment]
@lirantal you probably meant to ping @kfuchs. ;-)

`sudo npm` is the biggest lie out there. I love how Bower tells you're a coward if you try to `sudo bower`. :-)

**Comment by kfuchs** [comment]
I submitted the pull request here #350

**Comment by lirantal** [comment]
merged the new PR

**Pull request closed without merging**
