### PR TITLE
Update Mocha

### PR DESCRIPTION
**Pull request by ilanbiala**
Mocha caused Node 5 tests to fail (https://travis-ci.org/meanjs/mean/jobs/108313328)

### CODE REVIEW

**Comment by codydaig** [comment]
Still erroring out: 
http://puu.sh/n3e88/8cac83d59d.png
btw, they have the best error message ever.

**Comment by ilanbiala** [comment]
Based on https://github.com/mochajs/mocha/issues/2102#event-546388074, it looks like mock-fs is the issue. I'll look into that.

**Comment by ilanbiala** [comment]
@codydaig let's get this merged in after we merge in #1184 so we make sure it works on all OSes.

**Comment by codydaig** [comment]
#1184 has been merged.

**Comment by ilanbiala** [comment]
Awesome, closed an reopened so Travis will re-run.

**Comment by codydaig** [comment]
@ilanbiala Passed. Squash and we can merge.

**Comment by rhutchison** [comment]
LGTM

**Comment by ilanbiala** [comment]
@codydaig if LGTY, go ahead and merge once tests pass.

**Comment by nhhockeyplayer** [comment]
guys is this ready for primetime? I would like to bang on it.

**Pull request merged**
