### PR TITLE
Fix for users.profile.server.controller.js security (#1338)

### LINKED ISSUE #1338: users.profile.server.controller.js security
I came across this security bug while working on the user details update server-side controller.

When logged in and editing the current user's profile it is possible to submit another user's _id in the form. This causes the current user to be logged in as the other user.

### PR DESCRIPTION
**Pull request by masterwok**
Fixes #1338 an issue where if req.body._id was not set to the current user it
could potentially log the current user in as another user.

### CODE REVIEW

**Comment by lirantal** [comment]
This PR fixes https://github.com/meanjs/mean/issues/1338

**Comment by lirantal** [comment]
@masterwok I can't merge it as is because you need to style your commit message according to our guidelines. Please take a look and then re-submit it (or just rebase your commit with a new commit message)

**Comment by mleanos** [comment]
LGTM, once the commit message is updated. Thanks @masterwok.

**Comment by lirantal** [comment]
@masterwok care to update this PR please?

**Comment by masterwok** [comment]
@lirantal @mleanos  Sorry I sort of suck at using git and can't figure out how to rebase my commit  or update my pull request.

**Comment by codydaig** [comment]
@lirantal When you merge, if you choose squash, I'm fairly confident you can modify the commit message now as well. (I could be totally wrong though too.)

**Comment by lirantal** [comment]
Thank you @masterwok 
I've merged this very important security fix, hope to see more contributions :)

**Pull request merged**
