### PR TITLE
throw an exception if specified parent menu not found

### PR DESCRIPTION
**Pull request by kokokenada**

### CODE REVIEW

**Comment by codydaig** [comment]
@kokokenada Can you elaborate why we should throw an error instead gracefully handling it? Also, make sure you add tests. Lastly, make sure you follow the commit message guidelines. https://github.com/meanjs/mean/blob/master/CONTRIBUTING.md#commit-message-guidelines

**Comment by simison** [comment]
`$log.error()` would work better here.

**Comment by mleanos** [comment]
+1 on just using `$log.error()`

**Comment by kokokenada** [comment]
Hi @codydaig , The original motivation was because I ran into the problem when I was first getting going with MEANJS and the silent failure caused me to spend more time on it than necessary.  $log seems better than throw as the developer is alerted to the problem with stopping the execution.  I'll redo the pull request with the change (and change two un-handled throws that were in the original code.)  Thanks for the commit guide-lines.  Do really think tests for this are warranted in this case?   

Incidentally, there's a related problem where the ordering of adding the menus is problematic.  You get the problem that is logged with this PR if the sub menus are processed prior to parent.  I had to tweak the files in config/assets to work around it (the construction ordered seemed to be alphabetic.).  I'll add an issue for that...

**Comment by kokokenada** [comment]
(Oh -  I see now that pushing to my repository updates the PR..)

**Comment by codydaig** [comment]
@kokokenada Anything that can be tested needs too be tested. If there's an issue with ordering, I welcome an issue or PR too fix that as well. If you can write a test too prove that's it broken and then fixed, that's true TDD! :-D

**Comment by kokokenada** [comment]
I'll just enter the issue for now. :-) A lot on my plate right now...

**Comment by codydaig** [comment]
@kokokenada The tests are failing right now. You'll have too modify the tests too match the new error handling.

**Comment by kokokenada** [comment]
I have the test failure replicated.  Do you know off hand how the tests should be modified to look for the $log.error?

**Comment by codydaig** [comment]
Put  spy on $log.error and check what it gets called with

**Comment by simison** [comment]
@kokokenada great to see someone learning while doing a PR! Congrats and thanks for your efforts. :-)

**Comment by kokokenada** [comment]
@simison -thanks.  Yes a very useful process for me personally.  I've had implementing the tests for my work related MEAN modules on my to-do for a while and this will help.  And I have a lot of possible changes for MEANJS (not nearly ready yet) and I thought I'd start with a simple one.

**Comment by codydaig** [comment]
@simison Tis the beauty of open source projects! :-D 

@kokokenada Thanks for helping out!

**Comment by kokokenada** [comment]
I pushed an interim check in. So I can ask a question.  On my local build, when I inject $log, $log is equal to {}, which of course causes "error()" to not be found.  Not sure why this is happening.  

I'm suspicious that I have a local environment problem which may or may not be related.   When I run the client tests, I get an error:


    PhantomJS 2.0.0 (Windows 8 0.0.0): Executed 9 of 120 SUCCESS (0 secs / 0.137 secs)
    PhantomJS 2.0.0 (Windows 8 0.0.0) ChatController when user logged in should make sure socket is connected FAILED
	TypeError: Attempted to assign to readonly property. (line 9)
		at io (C:/Users/Ken/WebstormProjects/mean-fork/modules/core/tests/client/socket.io.client.service.tests.js:9:9)
		at connect (C:/Users/Ken/WebstormProjects/mean-fork/modules/core/client/services/socket.io.client.service.js:10:25)
		at C:/Users/Ken/WebstormProjects/mean-fork/modules/chat/client/controllers/chat.client.controller.js:16:21


Also, should installing phantomjs be part of the set up instructions?

**Comment by ilanbiala** [comment]
@codydaig @kokokenada any progress on this?

**Comment by rhutchison** [comment]
>I'm suspicious that I have a local environment problem which may or may not be related. When I run the client tests, I get an error:

This is resolved by https://github.com/meanjs/mean/pull/1198/files#diff-82e9255cbb27270ad882fe4908220795

**Comment by lirantal** [comment]
@kokokenada another ping to come back and finish this PR
@rhutchison did you mean that this issue is no longer relevant at all or were you referring to something else? I couldn't track this reference back in the history of this issue.

**Comment by kokokenada** [comment]
Hi - sorry for the delay. I've rebased my project on Meteor, so I've lost the synergy to work on this. 

I was able to avoid the exception and make it do something useful with orphans by adding:

````
  var savedForLater = [];
    this.saveForLater = function(menuId, parentItemState, options) {
      savedForLater.push({menuId: menuId, parentItemState:parentItemState, options: options});
    };

    this.trySavedForLater = function() {
      var tryList = savedForLater;
      savedForLater = [];
      for (var i=0; i< tryList.length; i++) {
        this.addSubMenuItem(tryList[i].menuId, tryList[i].parentItemState, tryList[i].options);
      }
    };
```

and calling it instead of throwing an exception: 
```
if (!pushed)
        this.saveForLater(menuId, parentItemState, options);
```

Then at the end of addMenuItem:

````
  // See if some orphans can be integrated
      this.trySavedForLater();
````

Whole file is here: I hope it helps:

````
//Menu service used for managing  menus
angular.module('core').service('Menus', ['$log',
  function ($log) {
    // Define a set of default roles
    this.defaultRoles = ['user', 'admin'];

    // Define the menus object
    this.menus = {};

    // A private function for rendering decision
    var shouldRender = function () {
      var user = CORE.getCurrentUser();
      if (!!~this.roles.indexOf('*')) {
        return true;
      } else {
        if(!user) {
          return false;
        }
        for (var userRoleIndex in user.roles) {
          for (var roleIndex in this.roles) {
            if (this.roles[roleIndex] === user.roles[userRoleIndex]) {
              return true;
            }
          }
        }
      }

      return false;
    };

    // Validate menu existance
    this.validateMenuExistance = function (menuId) {
      if (menuId && menuId.length) {
        if (this.menus[menuId]) {
          return true;
        } else {
          $log.error('Menu "' + menuId +'" does not exist');
        }
      } else {
        $log.error('MenuId was not provided');
      }

      return false;
    };

    // Get the menu object by menu id
    this.getMenu = function (menuId) {
      // Validate that the menu exists
      this.validateMenuExistance(menuId);

      // Return the menu object
      return this.menus[menuId];
    };

    // Add new menu object by menu id
    this.addMenu = function (menuId, options) {
      options = options || {};

      // Create the new menu
      this.menus[menuId] = {
        roles: options.roles || this.defaultRoles,
        items: options.items || [],
        shouldRender: shouldRender
      };

      // Return the menu object
      return this.menus[menuId];
    };

    // Remove existing menu object by menu id
    this.removeMenu = function (menuId) {
      // Validate that the menu exists
      this.validateMenuExistance(menuId);

      // Return the menu object
      delete this.menus[menuId];
    };

    // Add menu item object
    this.addMenuItem = function (menuId, options) {
      options = options || {};

      // Validate that the menu exists
      this.validateMenuExistance(menuId);

      // Push new menu item
      this.menus[menuId].items.push({
        title: options.title || '',
        state: options.state || '',
        type: options.type || 'item',
        class: options.class,
        roles: ((options.roles === null || typeof options.roles === 'undefined') ? this.defaultRoles : options.roles),
        position: options.position || 0,
        items: [],
        shouldRender: shouldRender
      });

      // Add submenu items
      if (options.items) {
        for (var i in options.items) {
          this.addSubMenuItem(menuId, options.state, options.items[i]);
        }
      }

      // See if some orphans can be integrated
      this.trySavedForLater();

      // Return the menu object
      return this.menus[menuId];
    };

    // Add submenu item object
    this.addSubMenuItem = function (menuId, parentItemState, options) {
      options = options || {};

      // Validate that the menu exists
      this.validateMenuExistance(menuId);

      // Search for menu item
      var pushed = false;
      for (var itemIndex in this.menus[menuId].items) {
        if (this.menus[menuId].items[itemIndex].state === parentItemState) {
          // Push new submenu item
          this.menus[menuId].items[itemIndex].items.push({
            title: options.title || '',
            state: options.state || '',
            roles: ((options.roles === null || typeof options.roles === 'undefined') ? this.menus[menuId].items[itemIndex].roles : options.roles),
            position: options.position || 0,
            shouldRender: shouldRender
          });
          pushed = true;
        }
      }
      if (!pushed)
        this.saveForLater(menuId, parentItemState, options);

      // Return the menu object
      return this.menus[menuId];
    };

    var savedForLater = [];
    this.saveForLater = function(menuId, parentItemState, options) {
      savedForLater.push({menuId: menuId, parentItemState:parentItemState, options: options});
    };

    this.trySavedForLater = function() {
      var tryList = savedForLater;
      savedForLater = [];
      for (var i=0; i< tryList.length; i++) {
        this.addSubMenuItem(tryList[i].menuId, tryList[i].parentItemState, tryList[i].options);
      }
    };

    // Remove existing menu object by menu id
    this.removeMenuItem = function (menuId, menuItemState) {
      // Validate that the menu exists
      this.validateMenuExistance(menuId);

      // Search for menu item to remove
      for (var itemIndex in this.menus[menuId].items) {
        if (this.menus[menuId].items[itemIndex].state === menuItemState) {
          this.menus[menuId].items.splice(itemIndex, 1);
        }
      }

      // Return the menu object
      return this.menus[menuId];
    };

    // Remove existing menu object by menu id
    this.removeSubMenuItem = function (menuId, submenuItemState) {
      // Validate that the menu exists
      this.validateMenuExistance(menuId);

      // Search for menu item to remove
      for (var itemIndex in this.menus[menuId].items) {
        for (var subitemIndex in this.menus[menuId].items[itemIndex].items) {
          if (this.menus[menuId].items[itemIndex].items[subitemIndex].state === submenuItemState) {
            this.menus[menuId].items[itemIndex].items.splice(subitemIndex, 1);
          }
        }
      }

      // Return the menu object
      return this.menus[menuId];
    };

    //Adding the topbar menu
    this.addMenu('topbar', {
      roles: ['*']
    });
  }
]);

**Comment by lirantal** [comment]
@codydaig would you like to pick it up from here?

**Comment by lirantal** [comment]
Closing old issue.
@kokokenada you're welcome to chime in again and test if there's any further work you wish to suggest on this topic.

**Pull request closed without merging**
