### PR TITLE
fix(core): fix page-title directive

### PR DESCRIPTION
**Pull request by itelo**
fix Eslint throws "Move the invocation into the parens that contain the function wrap-iife"
fix typo: retrict -> restrict

### CODE REVIEW

**Comment by itelo** [comment]
@mleanos seems that some commit have been lost in rebase

**Comment by ilanbiala** [comment]
@mleanos LGTM.

**Comment by lirantal** [comment]
@itelo you don't need to rebase to squash commits anymore because maintainers can do it for you when we merge in the PR.

@mleanos all yours.

**Comment by mleanos** [comment]
This seems like a straight forward and obvious fix. Merged.

**Pull request merged**
