### PR TITLE
Heroku Deployment Batch

### PR DESCRIPTION
**Pull request by almegdad**
Add Heroku Deployment Batch Script File

### CODE REVIEW

**Comment by lirantal** [comment]
Thansk @almegdad for helping out.
My overall comments:
1. Would be good to also update the README with a section on Heroku (and also work with @codydaig about updating the 0.4.0 documentation about it, probably another PR is required for that)
2. I'm not a fan of windows/batch files so personally I think converting it to a shell script is a better choice and also more consistent because we have shell scripts on the projects and not batch scripts
3. If we do decide on adding this script I'll put it in scripts/ folder and not on the package root level

**Comment by codydaig** [comment]
@almegdad @lirantal - When I've used Heroku in the past, I always have two different instances on heroku. Staging for testing and Production for actual production. This script assumes your always pushing to one machine. I'd recommend going with a grunt (or gulp) task. 
https://www.npmjs.com/package/grunt-heroku-deploy
(I haven't personally used this one, but I think it would be more efficient and along the lines of rest of the project to do deployment as a grunt/gulp task than a separate script.

**Comment by trainerbill** [comment]
Yeah Grunt or Gulp definitely

**Comment by lirantal** [comment]
@codydaig yeah I'm ok with that. @almegdad want to give it a try?

**Comment by almegdad** [comment]
Thanks for your quick response , 
maybe script needs to support more features , 
I,ll work on it as a gulp/grunt/batch .

**Comment by codydaig** [comment]
Close this PR?

@almegdad If you make it work with grunt, open a new PR.

**Pull request closed without merging**
