### PR TITLE
Fixing karma tests

### LINKED ISSUE #711: karma tests failing
looks like karma tests started throwing errors from this commit: https://github.com/meanjs/mean/commit/9fc88e6e5b5bd05c1e532246356725a3fa16a223

i'm currently looking into fixing them

### PR DESCRIPTION
**Pull request by cdriscol**
* Adding karma-ng-html2js-preprocessor to preprocess angular templates into js.  
* Adding user mock to articles tests.

Fixes #711 using [karma-ng-html2js preprocessor](https://github.com/karma-runner/karma-ng-html2js-preprocessor).

### CODE REVIEW

**Comment by cdriscol** [comment]
this PR didn't seem totrigger the travis CI build.. anyone know why?

**Comment by cdriscol** [comment]
@lirantal, @codydaig - look good to you guys?  once i get this in to 0.4.0, I'll start breaking down my client side tests into smaller PRs and submitting those.

**Comment by codydaig** [comment]
@cdriscol LGTM, but I don't feel as comftorable with the client side stuff to fully confirm. I think @ilanbiala and @rhutchison have a better grasp on this.

**Comment by ilanbiala** [comment]
@cdriscol where do you do the 2nd bullet? It's hard for me to tell because of the spacing that was changed as well.

**Comment by cdriscol** [comment]
@ilanbiala - [Here](https://github.com/cdriscol/mean/blob/fix_karma_errors_html2js/modules/articles/tests/client/articles.client.controller.tests.js#L50) is where I made the change to mock the user.

**Pull request merged**
