### PR TITLE
Gulp task enhancements - template cache

### PR DESCRIPTION
**Pull request by rhutchison**
Orig: #704 - These are updates to gulp build automation.

### Gulp Template Cache
Added angular-templatecache to cache templates for prod environment and combine with application.min.js.  No more html files loaded in prod.

### Auto Prefixer
As of bootstrap 3.2, vendor prefixes are deprecated in favor of autoprefixer.

Ref: https://github.com/twbs/bootstrap/blob/master/less/mixins/vendor-prefixes.less#L3

### CODE REVIEW

**Comment by codydaig** [comment]
LGTM

**Comment by vaucouleur** [comment]
This is brillant :+1: thanks @rhutchison  

Disabling the template cache is just a matter of removing 'templatecache' ? (for large web sites with lots of content)

**Comment by rhutchison** [comment]
@vaucouleur correct.  Glad you like it!  Let me know your experience.  I have not seen any downsides yet.

**Comment by vaucouleur** [comment]
@rhutchison I tested it with a mobile phone client, just to make the test a little bit more interesting, and it works just fine. Instinctively I would have tried to leverage the browser cache, and have more of a "pay as you use/go" approach -- but it's not obvious whether this is actually (easily) doable. Your approach seems to be recommended elsewhere,  and it's easy to disable it, so it's all good. Thanks !

**Comment by lirantal** [comment]
Great!

**Pull request merged**
