### PR TITLE
Deprecated $http success/error promise methods

### LINKED ISSUE #1479: Fix deprecated `$http.error()` and `$http.success()`
https://docs.angularjs.org/api/ng/service/$http

>The `$http` legacy promise methods `success` and `error` have been deprecated. Use the standard `then` method instead. If [`$httpProvider.useLegacyPromiseExtensions`](https://docs.angularjs.org/api/ng/provider/$httpProvider#useLegacyPromiseExtensions) is set to false then these methods will throw [`$http/legacy`](https://docs.angularjs.org/error/$http/legacy) error.

Used at least here:
- https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/users/client/controllers/settings/change-password.client.controller.js
- https://github.com/meanjs/mean/blob/c95bd7d1cb0c6e651f82b2b4cfa4e937d4dcf154/modules/users/client/controllers/settings/manage-social-accounts.client.controller.js
- https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/users/client/controllers/authentication.client.controller.js

### PR DESCRIPTION
**Pull request by mleanos**
Replaces the $http service calls with promise based methods of the client-side UsersService for the following:
  Users Change Password
  Users Manage Social Accounts
  Users Password Forgot
  Users Password Reset
  Users Signup
  Users Signin

Modifies tests to reflect changes.

Closes #1479

### CODE REVIEW

**Comment by mleanos** [comment]
I would like to point out that the `UsersService` methods that I added make calls to the `api/auth..` should really go into the `Authentication` service, or a new service, since they don't really interact with the same base URL `api/users`. However, doing so would require a major refactoring of the `Authentication` service, which could probably wait for now. It's a little ambiguous of where these should go on the back-end as well since our `api/auth` routes are handled by User server-controllers.

**Comment by codydaig** [comment]
@mleanos Is this ready for review?

**Comment by mleanos** [comment]
Yes :)

**Comment by lirantal** [comment]
@mleanos I'm fine with the change if you guys want to push in. Let's make sure we don't forget about this as I'd really want to kick 0.5.0 out the door already.
@hyperreality maybe you can help too with reviewing this.

**Comment by codydaig** [comment]
Haven't tested, but LGTM from the code perspective. Glad to see this updated!

**Pull request merged**
