### PR TITLE
Adding protractor options to fix travis failing

### PR DESCRIPTION
**Pull request by jloveland**
Fixing #961
travis-e2e

### CODE REVIEW

**Comment by lirantal** [comment]
It also passes all builds, including Node v4

**Comment by ilanbiala** [comment]
@lirantal Every build is passing, am I not looking in the right place?

**Comment by codydaig** [comment]
@lirantal Here is the e2e results from the Node 4.1.2 build. They seem to be passing. 
https://travis-ci.org/meanjs/mean/jobs/83819881#L4386

**Comment by lirantal** [comment]
Indeed they are passing. Not sure what were those errors I saw before when I inspected the v4 output from Travis.

I'm not experienced with protractor setup but the changes LGTM.

**Comment by codydaig** [comment]
I'm not experienced either but  LGTM

**Comment by jloveland** [comment]
Can we merge this so I can make sure my e2e tests here succeed? https://github.com/meanjs/mean/pull/910

**Comment by lirantal** [comment]
Yes

**Pull request merged**
