### PR TITLE
Fix(config): Use single pattern for routes

### PR DESCRIPTION
**Pull request by shanavas786**
Use single pattern for routes in `config/assets/default.js` 

`'modules/*/server/routes/**/*.js'` instead of 
`['modules/!(core)/server/routes/**/*.js', 'modules/core/server/routes/**/*.js']`

### CODE REVIEW

**Comment by lirantal** [comment]
@shanavas786 build is failing.

**Comment by codydaig** [comment]
I'm fairly confident that it was broken out into two because it needed to load all the module routes before loading the catch all that sends requests back to the front-end.

**Comment by codydaig** [comment]
I'm fairly confident that it was broken out into two because it needed to load all the module routes before loading the catch all that sends requests back to the front-end in the core module.

https://github.com/meanjs/mean/blob/master/modules/core/server/routes/core.server.routes.js#L14

**Comment by mleanos** [comment]
My understanding is the same as @codydaig. We need to load the module routes before core routes.

**Comment by codydaig** [comment]
I'll close for now.

**Pull request closed without merging**
