### PR TITLE
Renamed users (admin) html files to follow the conventions of the Article module

### PR DESCRIPTION
**Pull request by vaucouleur**
Renamed users (admin) files to follow the naming convention of the Article module:

- user-edit.client.view.html -> edit-user.client.view.html
- user-list.client.view.html -> list-users.client.view.html
- user.client.view.html -> view-user.client.view.html

Discussion: https://github.com/meanjs/mean/issues/817

### CODE REVIEW

**Comment by codydaig** [comment]
LGTM

**Comment by mleanos** [comment]
@vaucouleur What about using the dot notation? for instance, `edit.user.client.view.html`

**Comment by trainerbill** [comment]
@mleanos +1  That is what I would like to see and I think @lirantal agrees.

**Comment by vaucouleur** [comment]
@mleanos @trainerbill  Dots or dashes, any choice is fine with me. I just pointed out that it seemed wise to be consistent across modules. The Article module uses dashes, and there is a lot of "generated modules" out there that use the Article convention. If we do move to dots, we should also rename the Article html templates. Is that what we want ? If so, I can amend the PR.

**Comment by trainerbill** [comment]
@vaucouleur You have my vote on action.module.client.view.html

but I am not a contributor.

**Comment by codydaig** [comment]
@vaucouleur Sounds like the consensus is action.module.client.view.html (edit.user.client.view.html). If you could update and squash your commits, it should be good to go. Any objections @lirantal?

**Comment by lirantal** [comment]
No objections, I'm all up for the dot notation.

**Comment by vaucouleur** [comment]
The commits are squashed, and both the user admin and the article modules now follows the convention:
verb.object.client.view.html

**Comment by mleanos** [comment]
LGTM :+1: Tested and confirmed this is working.

Thanks @vaucouleur

**Comment by vaucouleur** [comment]
@mleanos Thanks to you for double checking this !

**Comment by rhutchison** [comment]
Not to throw a wrench in to this, but I preferred the naming convention of users admin to following the naming convention of the state.

**Comment by mleanos** [comment]
@rhutchison I see your point, but I think for views it makes more sense to have the *verb* first in the naming convention. The reason it makes sense to have the states named with their module/feature first, is of the hierarchical nature of states. Views don't follow that type of pattern, IMO.

**Comment by lirantal** [comment]
right, I'm still ok with the naming convention proposed here unless @rhutchison want to suggest some higher level more consistent naming convention across the project.

**Comment by rhutchison** [comment]
I am fine with flipping the words, but my point about inconsistency remains.  This PR was updated to implement [dot notation](https://github.com/meanjs/mean/pull/823#issuecomment-132626564), where-as the rest of the project is using dash. If you are going to switch to dot, then it should be across the project.

**Comment by vaucouleur** [comment]
@rhutchison This is a good point, consistency was my main initial concern. Ideally the file naming convention should be consistent across the project. I would be happy to amend the PR and apply the same naming convention to all html pages, if there is a consensus about this.

Something else: some pages have 2 words for the object name, for example "profile picture". Those words can be either separated by a dash (to denote "a close binding between those words"),  or to also use a dot.

- change.profile-picture.client.controller.js

... versus ...

- change.profile.picture.client.controller.js

My preference would be to keep a dash in this case between "profile" and "picture". But again this is a minor point, any of those choice is probably good as long as it is used consistently.

**Comment by lirantal** [comment]
I don't have a strong argument to support either so I'm fairly native.
Though is there a common style for that which other frameworks/projects adopt? I'm sure we're not inventing the wheel here.

**Comment by rhutchison** [comment]
https://github.com/johnpapa/angular-styleguide#style-y121

`avenger-profile.directive.js`

**Comment by lirantal** [comment]
I'm ok with having this:
```view-user.client.view.html```
and this to complement it
``` change-profile-picture.client.controller.js```

So this stays consistent where the first part of the filename (usually the verb/action) is formatted with a dash, and then the following filename info is with dots.

Sounds good?

**Comment by rhutchison** [comment]
sounds good, @vaucouleur what do you say?

**Comment by vaucouleur** [comment]
@lirantal  @rhutchison That's just fine. I will fix the PR with this pattern, and I will extend the PR to all html pages. Thanks for your feedback.

**Comment by lirantal** [comment]
Great.

**Comment by mleanos** [comment]
This is perfect. Thanks for getting this sorted out guys.

**Pull request closed without merging**
