### PR TITLE
feat(build): updating supported Node.js versions for CI

### PR DESCRIPTION
**Pull request by lirantal**
Deprecating older Node.js versions to streamline development for the LTS and newer versions.
See #1756

### CODE REVIEW

**Comment by simison** [comment]
Wonder if `gcc` is required anymore btw?

https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

**Comment by mleanos** [comment]
LGTM. 

FWIW, I'm running a couple MEANJS applications on Node v7.10.0 without issue.

**Comment by simison** [comment]
@lirantal you should probably add Node 8 here too (see it passing here; https://github.com/meanjs/mean/pull/1785/files)

**Comment by lirantal** [comment]
Finally able to merge this in... oh my god this has taken too long

**Pull request merged**
