### PR TITLE
Docker:Install gem sass for  grunt-contrib-sass 

### PR DESCRIPTION
**Pull request by liuhill**
Install gem sass for grunt-contrib-sass

### CODE REVIEW

**Comment by lirantal** [comment]
LGTM.
It's also aligned with a recent PR I added which does the same thing but for Travis.

**Comment by mleanos** [comment]
LGTM.

**Comment by codydaig** [comment]
LGTM

**Comment by lirantal** [comment]
@liuhill squash that merge commit and let's merge it in.

**Pull request closed without merging**
