### PR TITLE
Improving README file

### PR DESCRIPTION
**Pull request by RoySegall**
The project now support V5.

### CODE REVIEW

**Comment by lirantal** [comment]
Thank you, great attention to details!

**Comment by codydaig** [comment]
Should we replace it with Node 6 not being supported?

**Comment by lirantal** [comment]
@codydaig good point, although I think node v4 is the mainstream now and also the LTS version so possibly this is just an overflow of information to the user in the README.

**Comment by codydaig** [comment]
@lirantal Fair enough

**Pull request merged**
