### PR TITLE
fix(core): Adding server info to log initialization

### PR DESCRIPTION
**Pull request by farajfarook**
Adding host information to the log initialization and aligning the
texts.

### CODE REVIEW

**Comment by codydaig** [comment]
Are there any issues with swapping `\t\t\t\t` with spaces? Are there systems that regular spaces don't work with?

**Comment by farajfarook** [comment]
`\t` didnt work properly in my command line. I tried it in windows command prompt as well as in centos bash shell.

**Comment by codydaig** [comment]
@farajfarook Thanks for the report back. Any chance you can include a quick screenshot with what the new format looks like? Thanks!

**Comment by farajfarook** [comment]
This is how it looks now. Please let me know if you want anything to change. In my free time i will fix it. 

untitled

**Comment by codydaig** [comment]
LGTM

**Comment by ilanbiala** [comment]
LGTM.

**Pull request merged**
