### PR TITLE
Angular material design

### PR DESCRIPTION
**Pull request by siteshackinc**

### CODE REVIEW

**Comment by trainerbill** [comment]
@siteshackinc Please close this for now

**Comment by theonaciri** [comment]
Thanks a lot!

**Comment by PierreBrisorgueil** [comment]
@theonaciri  https://github.com/weareopensource/roMEANet we make a starter angular material with a different style if you want

**Comment by theonaciri** [comment]
Exactly what I was looking for. And nice project name. I'll use it right now for my small project. Thanks again !

**Pull request closed without merging**
