### PR TITLE
Enabling mongoose debug mode

### PR DESCRIPTION
**Pull request by lirantal**
Enhancing support for development environment to enable mongoose debug mode so that we can debug db queries

PR submitted out of original idea from https://github.com/meanjs/mean/pull/143

### CODE REVIEW

**Comment by mleanos** [comment]
+1 LGTM. I'm excited to try this out.

**Comment by ilanbiala** [comment]
@lirantal doesn't it print a lot more stuff? Shouldn't we check against an environment variable to see because I wouldn't want debug to always run..

**Comment by lirantal** [comment]
@ilanbiala you're right I don't think it should be enabled by default, I'll update the PR.

**Comment by trainerbill** [comment]
I honestly don't mind debug mode running in dev mode...  But an env variable would be nice for production boxes.  so you don't have to change code to go into debug mode.  So I would add it to production.js with

production.js
process.env.MEAN_MONGOOSE_DEBUG || false

development.js
process.env.MEAN_MONGOOSE_DEBUG || true

**Comment by lirantal** [comment]
I actually agree with @ilanbiala that user wouldn't want mongodb debug on, even on development environment, and I do like the environment variable idea so I'm combining it to this
```
debug: process.env.MONGODB_DEBUG || false
```

**Comment by ilanbiala** [comment]
What about secure?

**Comment by lirantal** [comment]
@ilanbiala you mean the environment config 'secure'? we don't have that on 0.4.0

**Comment by ilanbiala** [comment]
Oh yeah right, then this is fine.

**Comment by lirantal** [comment]
Thanks guys.

**Pull request merged**
