### PR TITLE
feat (ide) Add vscode launch config

### PR DESCRIPTION
**Pull request by Wuntenn**
Adds configuration for vscode:
- Adds most gulp tasks
- Adds chrome debugging: Debug client-side within vscode
- Adds debug attach: Debug server-side within vscode
- Adds compound tasks to start multiple combos of the above

### CODE REVIEW

**Comment by Wuntenn** [comment]
Should make it easier for people who want to use vscode to get up and running without having to dig
through documentation.

**Comment by lirantal** [comment]
Sure @Wuntenn 

Can you remove however the package-lock and package.json from the commit?

**Comment by Wuntenn** [comment]
Done! 💃 :D

**Comment by lirantal** [comment]
Thanks!

**Pull request merged**
