### PR TITLE
Bump glob to version 5.0

### PR DESCRIPTION
**Pull request by adamwalz**
In glob v4.5 the sync option was deprecated in favor of `glob.sync(patterns, opts)`

https://github.com/isaacs/node-glob/tree/v4.5.0#options

### CODE REVIEW

**Comment by ilanbiala** [comment]
@lirantal we should probably have this PR on the 0.4 branch to make it easier to merge right? Otherwise, LGTM.

**Comment by lirantal** [comment]
right, this should be against 0.4

**Comment by ilanbiala** [comment]
@adamwalz can you redo this PR off of the 0.4 branch and I'll be able to merge it in more easily.

**Comment by adamwalz** [comment]
Yeah it's already available on #463

**Comment by ilanbiala** [comment]
@lirantal should we merge in this PR or is merging in #463 enough. I assume we're just going to do a git merge and choose 0.4 to keep?

**Comment by lirantal** [comment]
exactly @ilanbiala , I saw you merged it so let's close this one.

**Pull request closed without merging**
