### PR TITLE
feat(github): adding support for Pull Requests templates

### LINKED ISSUE #1225: Add Pull Request Template
Basically just move https://github.com/meanjs/mean/blob/master/CONTRIBUTING.md#commit-message-guidelines to a file called `PULL_REQUEST_TEMPLATE`.

https://github.com/blog/2111-issue-and-pull-request-templates
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

(Sorry, no time here for a PR)

### PR DESCRIPTION
**Pull request by lirantal**
fixes #1225

### CODE REVIEW

**Comment by lirantal** [comment]
@simison looks ok to you?

**Comment by ilanbiala** [comment]
@lirantal shouldn't that be moved out of CONTRIBUTING.md as well if we're moving it into a new GH-based feature?

**Comment by codydaig** [comment]
LGTM

@ilanbiala Personally, I'd like to leave it in both places as most people are accustomed to looking for the CONTRIBUTING.md document. My vote would be to revisit the duplicate data in a couple months and see if it's worth keeping in both places or not.

**Comment by ilanbiala** [comment]
Okay, SGTM.

**Comment by lirantal** [comment]
The reason I left it in the CONTRIBUTING.md is because I think it has it's place.
While some people make a PR from GitHub's UI, others can benefit when they are working offline or in general would like to review the contribution guideline before they begin their contribution.

**Pull request merged**
