### PR TITLE
fix(tests) fixing assertion test for logger which failed

### PR DESCRIPTION
**Pull request by lirantal**
logger test failed on undefined variable

### CODE REVIEW

**Comment by mleanos** [comment]
LGTM

**Comment by mleanos** [comment]
Out of curiosity..

Under what conditions did this test fail? Was it when the logger options were not set in the environment config?

**Comment by codydaig** [comment]
LGTM

**Comment by lirantal** [comment]
@mleanos it failed locally, maybe I have a newer shouldjs library, not sure. It wasn't related to the actual logging options in the env config (although that could be a different issue).

It anyway insisted that the options.should object is undefined for some reason.

**Pull request merged**
