### PR TITLE
Aligning ExpressJS 4.0 compatibility

### PR DESCRIPTION
**Pull request by lirantal**
replacing old expressjs 3.x built-in 'compress' middleware with standalone compression middleware

### CODE REVIEW

**Comment by lirantal** [comment]
I don't think we can make that distinction. I mean, I don't see any point in introducingthat kind of different behavior:)

**Comment by ilanbiala** [comment]
`/\.min/` gives us minified files, right? Compressing .min files seems like more of a waste because they are already pretty compressed, whereas you could probably compress unminified files more because they aren't as compressed to begin with.

**Comment by lirantal** [comment]
@ilanbiala I don't think it matters much if files are minified or not.
Thanks for reviewing, I'll go ahead and merge.

**Comment by ilanbiala** [comment]
Sounds good, we can always optimize once everything is else as fast.

**Pull request merged**
