### PR TITLE
fix(config): typo

### PR DESCRIPTION
**Pull request by eduardojunio**
fix(config): typo

Fixed a typo in a comment.

### CODE REVIEW

**Comment by lirantal** [comment]
that function still technically processes files though so I'm not 100% sure

**Comment by ilanbiala** [comment]
It really doesn't matter, honestly the function does both, so I would say this is unnecessary.

**Comment by lirantal** [comment]
I feel somewhat as Ilan does unless anyone else cares to chime in?

**Comment by ilanbiala** [comment]
@lirantal I think we can close this. We'll reopen if someone feels differently.

**Pull request closed without merging**
