### PR TITLE
Add .eslintrc

### LINKED ISSUE #763: Request for JSCS
Hi @rhutchison,

Can you please create a PR for the adding the JSCS (https://github.com/jscs-dev/node-jscs) support? I'd like to push this in along with JSHint that we have today to enforce the code style standards.

I know that you included part of that in another PR that we asked to take out, so there's no point for me to re-do any of the work you already have pending there.
Thanks!

### PR DESCRIPTION
**Pull request by ilanbiala**
Fixes #763
@lirantal @codydaig @rhutchison

### CODE REVIEW

**Comment by ilanbiala** [comment]
So I added Grunt and Gulp support, which means that we now get errors in our builds. The question is whether we want that to fail our builds (which I think should be the case). If so, I suggest we devote another PR to fixing those issues and make this PR strictly for adding in ESLint.

**Comment by trainerbill** [comment]
Yes it should fail the build and we should submit PR's to fix the entire project.

**Comment by codydaig** [comment]
@ilanbiala I think it should fail the build. However, do we want to fix the issues before we force it to fail? I'd hate for this to get merged in and have every PR after this fail because of eslint errors in other parts of the code.

**Comment by mleanos** [comment]
:+1: On fixing the issues in separate PR(s) before this gets merged.

**Comment by lirantal** [comment]
Agree with the above.

**Pull request closed without merging**
