### PR TITLE
add return for done(err) in test

### PR DESCRIPTION
**Pull request by loulin**
in case of double callback

### CODE REVIEW

**Comment by ilanbiala** [comment]
Seems good, @lirantal LGTY? @loulin can you squash down to 1 commit?

**Comment by loulin** [comment]
done.
BTW, what does LGTY mean?

**Comment by ilanbiala** [comment]
Looks good to you

**Comment by lirantal** [comment]
let's just wait for next week until we have a 0.4 merged-with-master branch and then we can merge this in.

**Comment by rhutchison** [comment]
@lirantal can you merge?

**Comment by ilanbiala** [comment]
@lirantal shouldn't this either wait until 0.4.0 is fully merged into master or be merged into the release branch we have right now?

**Comment by lirantal** [comment]
@ilanbiala now that master_to_0.4.0 is merged I want to merge this into 0.4.0 branch, do you think there's a problem with that?

**Comment by ilanbiala** [comment]
Ah okay, yeah then that should be fine.

**Pull request merged**
