### PR TITLE
Added missing dependency injection in Chat

### PR DESCRIPTION
**Pull request by mleanos**
During my last PR merge, the dependency injection for Authentication and
$location weren't merged properly. I added them back to the Chat client
controller.

### CODE REVIEW

**Comment by mleanos** [comment]
@lirantal @ilanbiala Can this go out asap? I'm not sure how this happened. I tested it right before I committed, but it could have been my mistake in the end.

**Comment by mleanos** [comment]
Looking back at the commit, it was definitely my fault. I apologize. I'll do my best to make sure that doesn't happen again.

**Comment by rhutchison** [comment]
LGTM

**Comment by cdriscol** [comment]
would love to see this soon!

**Comment by mleanos** [comment]
@cdriscol What do you mean by "blew up"? I noticed the client test for Chat doesn't have any tests implemented, in the current 0.4.0 branch. 

I see you have tests implemented in your branch for #663 does have tests defined. This would blow up your karma tests, without this fix.

**Comment by cdriscol** [comment]
@mleanos, the CI shows the tests failing.  I don't think it was actually related to this change (I'm looking into it now to see what's causing the failures)

You can see the test results from the "View details" on the merge, it shows the travis CI output.  it does say "passed", but if you click the details it will show the karma test failures.  You can also see them if you run **gulp karma** locally

**Comment by mleanos** [comment]
@cdriscol Good to know. I'll look into that. So I'm not that familiar with travis CI. If we had a client test for Chat, that makes sure the dependencies load, travis CI would have caught that since the dependency wasn't there?

**Comment by cdriscol** [comment]
@mleanos, if we had our CI setup to fail on jshint failure - then yes, we could have caught it.  it was throwing 2  *not defined* errors in jshint on your merge.

tracked the errors starting back at this commit: https://github.com/meanjs/mean/commit/9fc88e6e5b5bd05c1e532246356725a3fa16a223

**Comment by mleanos** [comment]
@cdriscol My commit was done after commit 9fc88e6 

I did a rebase, and I failed to merge the dependencies from my PR branch. Definitely caused by my error.

**Pull request merged**
