### PR TITLE
Changed favicon string to env variable

### PR DESCRIPTION
**Pull request by rodp82**

### CODE REVIEW

**Comment by ilanbiala** [comment]
LGTM, confirmation that it still works?

**Comment by mleanos** [comment]
LGTM. I've tested, and confirms it still works.

**Comment by lirantal** [comment]
Correct, we already have the favicon defined in the config: https://github.com/meanjs/mean/blob/63d0d71cf6d20c28cf26137aa6c5981a5ea66f2d/config/env/default.js#L31

LGTM @codydaig

**Comment by codydaig** [comment]
LGTM. 

Thanks @rodp82 !

**Comment by rodp82** [comment]
@codydaig You're welcome!

**Pull request merged**
