### PR TITLE
feat(users): Profile picture cropping, mobile uploading and progress bar

### PR DESCRIPTION
**Pull request by hyperreality**
feat(users): Profile picture cropping, mobile uploading and progress bar

Improvements to the Change Profile Picture page including:
 - The option to take a camera pic and upload it is now offered on mobile
 - Large images (such as those taken from a camera) no longer crash the page
 - Add ability to crop pictures using [ngImgCrop](https://github.com/alexk111/ngImgCrop)
 - Add progress bar during uploading
 - Large images are now properly resized to thumbnails
 - Much of this was accomplished by switching from the [angular-file-upload](https://github.com/nervgh/angular-file-upload) 
module to the far more fully-featured and frequently-updated [ng-file-upload](https://github.com/danialfarid/ng-file-upload)

### CODE REVIEW

**Comment by lirantal** [comment]
@hyperreality great work, thanks it looks good.

**Comment by mleanos** [comment]
Thank you @hyperreality! This looks really good! I just took it for a spin :)

**Comment by hyperreality** [comment]
@mleanos @lirantal Really appreciate all your recent work on the project too, and hope I can push more work from mine back into the main framework.

**Comment by lirantal** [comment]
@hyperreality no problems. Looking forward to read more of your PRs with everyone else here :)

**Comment by simison** [comment]
Ahh, hey, this PR should've not been merged with that `ngImgCrop` module. It's badly outdated and abandoned: https://github.com/alexk111/ngImgCrop/issues/150

@hyperreality perhaps it would be easy to switch to that https://github.com/CrackerakiUA/ngImgCropFullExtended instead

**Comment by hyperreality** [comment]
@simison Thanks for the heads up. ngImgCrop was being recommended and used by the author of ng-file-upload, so perhaps he needs a nudge too.

I've incorporated your suggestion into #1465

**Comment by simison** [comment]
@hyperreality excellent!

**Comment by lirantal** [comment]
Thanks @simison, I need more eyes and feedback on the frontend side PRs so will appreciate more help there.

**Pull request merged**
