### PR TITLE
Added Visual Studio files to gitignore

### PR DESCRIPTION
**Pull request by mleanos**
Adding files to ignore that are related to Visual Studio, and Node.js
development within the VS environment.

This is my first PR for a forked repo. I figured it's a good starting point, to get used to the flow of PR's, and contributing to this project. Also, it will help keep my fork clean from VS files moving forward. 

@lirantal @ilanbiala Please let me know if this is an appropriate PR, and that I'm following the proper flow for this project. Thanks.

### CODE REVIEW

**Comment by codydaig** [comment]
LGTM

**Comment by ilanbiala** [comment]
@lirantal I'm fine with the change, but what I don't like is all the editors going before the general files. Thoughts?

**Comment by mleanos** [comment]
@ilanbiala I agree. As the list of editors grows, it will push the general settings down further. Would be nice to add all editor files after any other settings.

**Comment by mleanos** [comment]
Per @ilanbiala request, I moved the editor files to the bottom of the gitignore file. I think this is better.

**Comment by lirantal** [comment]
Cool, LGTM.

**Pull request merged**
