### PR TITLE
Renamed files using convention verb-object.client...

### LINKED ISSUE #817: File naming conventions: Users (Admin) module versus Article module
There are two minor (harmless) inconsistencies in the naming of the view files : 

- either object-verb ("user-edit") versus verb-object ("edit-article")
- the view page being either object alone ("user") versus view-object ("view-article")

Users (admin) pages:

* user-edit.client.view.html
* user.client.view.html
* user-list.client.view.html

versus Article pages:

* edit-article.client.view.html
* view-article.client.view.html
* list-articles.client.view.html

### PR DESCRIPTION
**Pull request by vaucouleur**
Renamed files using file naming convention: verb-object.client...

Closes #817

### CODE REVIEW

**Comment by rhutchison** [comment]
LGTM

**Comment by mleanos** [comment]
LGTM

**Comment by lirantal** [comment]
@vaucouleur this PR has conflicts now after we merged the facebook PR and #759 
can you take a look?

**Comment by vaucouleur** [comment]
@lirantal I just rebased using upstream. Can you please try again.

**Comment by rhutchison** [comment]
Thanks @vaucouleur LGTM

**Comment by mleanos** [comment]
LGTM as well

**Comment by codydaig** [comment]
LGTM

**Comment by vaucouleur** [comment]
@lirantal Rebased using upstream following #774

**Comment by codydaig** [comment]
Still LGTM 

Thanks @vaucouleur for keeping up on this PR with all the changes and rebases.

**Comment by mleanos** [comment]
Tested. LGTM.

**Comment by ilanbiala** [comment]
@lirantal just fyi I merged so @rhutchison could continue working on something that needs this.

**Comment by lirantal** [comment]
Of course, no problems.

**Pull request merged**
