### PR TITLE
0.4.0

### PR DESCRIPTION
**Pull request by sylvainlap**
Injecting the $window service.
No need of "this".

### CODE REVIEW

**Comment by ilanbiala** [comment]
Dupe of #377, we'll try to get that one merged.

**Comment by sylvainlap** [comment]
I did this one in order to commit the change on the 0.4.0 branch, and not only master.

**Comment by ilanbiala** [comment]
LGTM, @lirantal any comments?

**Comment by lirantal** [comment]
can't comment as I don't do angular.

**Pull request merged**
