### PR TITLE
Travis notifications in Gitter

### PR DESCRIPTION
**Pull request by ilanbiala**
@lirantal I added this snippet to add Travis notifications in Gitter. Hopefully we'll make Gitter more informative by doing things like this.

### CODE REVIEW

**Comment by lirantal** [comment]
was on my todo list, thanks for taking care of that!

**Comment by codydaig** [comment]
LGTM

**Comment by ilanbiala** [comment]
@lirantal LGTY?

**Comment by lirantal** [comment]
Yeah, I'm not 100% on the syntax for the YAML file to work with Travis CI but looks generally ok.
Go and merge.

**Pull request merged**
