### PR TITLE
Paypal authentication

### PR DESCRIPTION
**Pull request by trainerbill**
Added PayPal authentication Strategy and links on the signup page.  You may want to find a logo that better suites the application.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@trainerbill I haven't heard of anyone using PayPal to authenticate. Can you provide a couple companies that do?

**Comment by jloveland** [comment]
my company is interested in using paypal for oauth. The reason is that we want to give users the option to use paypal for their login and payment option. AFIAK, this is a great addition. Making it easier for users to pay is a win.

**Comment by ilanbiala** [comment]
@jloveland that's completely fine, but I don't think most people who set up MEAN.js will need PayPal authentication, which is why I'm hesitant to merge this.

**Comment by trainerbill** [comment]
@ilanbiala I know that nomorerack uses login with paypal.  I know that PayPal is releasing a OneTouch functionality, that enables a user to stay logged in to make purchases.  I think this may push Login With PayPal as once they use this service they won't need to login again to submit a payment.  PayPal has over 150 million users so the user base is there.  This only adds one additional node module so It's not bloating.  Either way, giving users more options for authentication is never a bad thing.  Let me know if you want me to provide more business examples.

**Comment by ilanbiala** [comment]
@lirantal do you think we need this in there? As it is I think LinkedIn is overkill...

**Comment by lirantal** [comment]
@ilanbiala you mean PayPal, and yeah I'm ok with this getting merged, it's a good addition if users will find it useful in the future, and it doesn't add any clutter in the code.

@trainerbill my only concern though is that the package.json is quite modified, in terms of spacing as well as packages ordering there. Can you please fix that and make sure the only modifications there are those that you are actually intend to change.

After that we can merge.

**Comment by trainerbill** [comment]
Just cleaned up package.json.  Not sure why my npm is hosing the whole file.  Do you provide any documentation on how to setup authentication strategies?  Like exporting ID and SECRET?  If so I have a sandbox ID and SECRET that can be used for testing/quick setup for development.  May want to include it in any documentation you have.

**Comment by lirantal** [comment]
Looks cleaner, thanks.
What do you mean exporting ID and SECRET?

**Comment by trainerbill** [comment]
The configuration for authentication uses environment variables.  I was just offering my PAYPAL_ID and PAYPAL_SECRET for sandbox mode.  Sometimes its a bit confusing to setup a paypal sandbox account and if someone just wants to try it out, it may be beneficial to include some testing ID and SECRET in a doc or commented in the code somewhere.  So they can just run export PAYPAL_ID=blah and export PAYPAL_SECRET and have a working example.  it would work in grunt debug mode since the return URL should always be localhost:3000/auth/paypal/callback at that point.  Just a thought.  Let me know if you want me to do anything else.  Thx!

**Comment by trainerbill** [comment]
Anything else I need to do to get this merged in?  Will it go into the generator as well?

**Comment by ilanbiala** [comment]
@trainerbill can you squash and rebase?

**Comment by trainerbill** [comment]
@ilanbiala Done

**Comment by ilanbiala** [comment]
@trainerbill still not able to cleanly merge and there are multiple commits.

**Comment by trainerbill** [comment]
I created a new branch with one commit and sent in a new PR:

https://github.com/meanjs/mean/pull/596

**Pull request closed without merging**
