### PR TITLE
Make emails unique

### PR DESCRIPTION
**Pull request by igorauad**
Emails are made unique. When user attempts to sign in through a provider in which his email is one that is already registered, user is redirected to the signin page with an error passed as a query string parameter.

Is this a reasonable solution to https://github.com/meanjs/mean/issues/118?

Your feedback is welcome. Thanks in advance.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@igorauad I think if we merge in #337 then this may have some issues working. It would be better to merge that in first IMO and then make the necessary changes. It would be great if you could provide your 2¢ on that.

**Comment by igorauad** [comment]
Ok, @ilanbiala . Thank you!

**Comment by lirantal** [comment]
this PR needs some conflicts fixing before we can merge but overall looks like we can go for it.
@igorauad ?

**Comment by igorauad** [comment]
@lirantal I've just fixed the conflicts

**Comment by lirantal** [comment]
thanks @igorauad 
@rhutchinson @codydaig @mleanos LGTY?

**Comment by codydaig** [comment]
@igorauad I pulled your branch down to test and it works! But, can we make it so it says the email is already in use versus "Unique field already exists". The user would have no way to know if it's the username or email field that is already taken. (Or even which fields must be unique.)

**Comment by igorauad** [comment]
@codydaig see if the commit that I've just added solves the problem for you

**Comment by codydaig** [comment]
@igorauad Tested and works great! Thanks :)

LGTM

**Comment by lirantal** [comment]
Thanks @igorauad , @codydaig.

**Comment by igorauad** [comment]
Thanks @codydaig , @lirantal

**Pull request merged**
