### PR TITLE
fix(dependencies)

### PR DESCRIPTION
**Pull request by siteshackinc**
Updated version dependencies, added Kerberos to satisfy a dependency

### CODE REVIEW

**Comment by codydaig** [comment]
@siteshackinc The build failed.

**Comment by siteshackinc** [comment]
Mistakinly added a couple wrong versions, updated a few more with my next PR

**Comment by ilanbiala** [comment]
@siteshackinc which dependency requires kerberos? Our builds have been passing so far and we haven't noticed any issues. Also, Angular 1.4 has some changes that we need to account for, so please do that in a separate PR.

**Comment by siteshackinc** [comment]
npm WARN EPEERINVALID mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPEERINVALID mongodb-core@1.2.32 requires a peer of kerberos@~0.0 but none was installed.

**Comment by ilanbiala** [comment]
@siteshackinc we already fixed some of these and a more current PR is open, so we're just going to close this one. Thanks for making the initial push!

**Pull request closed without merging**
