### PR TITLE
feat(config): upgrade angular-bootstrap from 0.13 to 1.0

### LINKED ISSUE #1131: bootstrap accordion is not working
<uib-accordion heading="hello">  does not work.

In bower.json, the version of angular-bootstrap is "0.13"... it should be "0.14" because the version 13 has issues.  version 0.14 is the latest.

### LINKED ISSUE #1142: update to angular-bootstrap 1.0
Angular-bootstrap 1.0 is out. Would it be desirable for you to update? I created a patch:
https://gist.github.com/trendzetter/c1e7be8bd3e41404fd49

### PR DESCRIPTION
**Pull request by trendzetter**
Moving from 0.13 solves many the many issues with this version, provides a more stable interface.
Migration guide: https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes

Closes #1142 
Closes #1131

### CODE REVIEW

**Comment by lirantal** [comment]
@trendzetter you should review our CONTRIBUTING documentation since it seems you need to squash your commits and change the commit text to our standards.

**Comment by trendzetter** [comment]
@lirantal I'm a bit new to this, I tried to "squash" my commits and format my text according to the docs. Am I doing it better now?

**Comment by mleanos** [comment]
@trendzetter This is generally how I squash my commits down to 1 commit.
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
You basically squash all your commits, into one.. in your case here (based on the commits) it would be `git rebase -i HEAD~5`

Also, I see you have merge commits here. It's better to not use merge for contributing, as it will sometimes pull in other changes that have already been merged upstream; thus, making it look like your made the changes & there can be conflicts when merging the PR.

Use rebase instead, as described here http://blog.bigbinary.com/2013/09/13/how-to-keep-your-fork-uptodate.html
1) checkout master, and rebase from upstream master branch
2) checkout your PR branch, and rebase from your local master branch
3) if Git tells you that your branches have "diverged", then you will need to `git push --force` to force your remote branch to be exactly what your local branch is.

This took some time for me to get comfortable with, but it's really not as scary as it appeared to me at first :) The articles I shared really helped me a lot.

**Comment by trendzetter** [comment]
I am grateful for you helpful attitude. 
Did I pull it off?

**Comment by mleanos** [comment]
LGTM

**Comment by ilanbiala** [comment]
@mleanos did you test this as well, or just the change for the commit message?

**Comment by mleanos** [comment]
The squash looks good, and the diffs look fine to me. However, I haven't tested. I wanted to, but I don't have time today. 

@trendzetter Have you done a quick once over, and made sure nothing on the UI was adversely affected by this?

**Comment by ilanbiala** [comment]
I haven't worked with ui-bootstrap after 0.13, so I'm not sure if it will change the CSS and look in addition to the directives and such as well.

**Comment by trendzetter** [comment]
@lirantal Yes. All seemed to work after fixing the menu. After more systematic screening the code I have found more directives that need updating where I wasn't aware off. I will update my pr.

**Comment by trendzetter** [comment]
I have updated my commit based on a carefully checking all ui-bootstrap components. It took me some wrestling with git. I will take a break and give it some more extensive testing.

**Comment by trendzetter** [comment]
Further testing revealed no regressions.

**Comment by trendzetter** [comment]
@ilanbiala They renamed their directives. Nothing is deprecated. Some directives are extended with additional options since 0.13. The migration guide sums the breaking changes up:
https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes

**Comment by ilanbiala** [comment]
SGTM, haven't tested, but based on the docs, seems fine.

**Comment by mleanos** [comment]
@trendzetter @ilanbiala 

I ran through all the tests, and manually tested this branch. Everything looks good to me, with the exception of the confirm dialog not implemented in the article client controller. After looking at the code, I realized that this branch isn't current with *master*.

@trendzetter Can you rebase with the upstream *master* branch, and push? Normally, it wouldn't be much of an issue, since the changes would just be merged on top of *master*. However, these changes have a wide reach over the UI. I'd like to test with the most up to date code-base, to be sure we don't introduce any bugs/issues.

**Comment by trendzetter** [comment]
I've synced with the upstream master. The confirm dialog for delete is correctly displayed. I am not seeing any new issues which is expected as the articles module is not using any of the renamed angular-bootstrap directives.

**Comment by ilanbiala** [comment]
@trendzetter LGTM, just maybe change the scope of the commit message? @codydaig suggestions?

**Comment by codydaig** [comment]
@ilanbiala I'm going to pull this branch down tomorrow and test. I'll ping back tomorrow with any comments.

**Comment by trendzetter** [comment]
@codydaig Did you find any issues that I need to look in?

**Comment by ilanbiala** [comment]
@codydaig is this good to merge?

**Pull request merged**
