### PR TITLE
Changed .html files to have 2 spaces instead of tabs

### PR DESCRIPTION
**Pull request by codydaig**
@trainerbill This should fix your issue.

### CODE REVIEW

**Comment by trainerbill** [comment]
@lirantal Can we merge this ASAP?  I think it is part of my problem with indentations.

**Comment by lirantal** [comment]
Cool.
I'll merge it in.

@codydaig is there a flag to also tell editoconfig to also always make sure there's a newline in the end of the file?

**Comment by QiyuLi** [comment]
@lirantal 
Looks like it is already configured.
https://github.com/meanjs/mean/blob/master/.editorconfig#L12

**Comment by codydaig** [comment]
@QiyuLi Thanks! :-D Yup, @lirantal it looks like it's already there.

**Comment by lirantal** [comment]
Awesome!

**Pull request merged**
