### PR TITLE
feat(gulp): Add mongoose task to Gulp

### PR DESCRIPTION
**Pull request by itelo**

### CODE REVIEW

**Comment by ilanbiala** [comment]
@itelo why is this necessary in Gulp?

**Comment by itelo** [comment]
@ilanbiala due to #1175, but i read more and dont know if we need mongoose task...

**Comment by mleanos** [comment]
I don't think we need the `mongoose` task. I know it's on the list in the issue tracking the Gulp migration, but I don't see any use/reason-for-use. We're not even using it with Grunt; the task is only defined, but never used.

**Comment by itelo** [comment]
So, should i close the PR ?

**Comment by ilanbiala** [comment]
We'll reopen if necessary, thanks for the effort though.

**Pull request closed without merging**
