### PR TITLE
feat(users):  Update social login design

### PR DESCRIPTION
**Pull request by benobab**
## New design for social links

- responsive images 
- grid for mobile layout as well

### CODE REVIEW

**Comment by mleanos** [comment]
LGTM. I've tested this as well.

Thanks @benobab!

**Comment by hyperreality** [comment]
One small gripe I have with this commit is that it works great if you want to authenticate with all 6 networks, but in most cases that won't be the case, and after removing a button or two it's hard to get a nice centred design.

Furthermore, I tried shrinking the page in Firefox and below a certain size it's not possible to click the buttons at all.

Also why we're at it why don't we make the buttons interactive? Add them to the social class and put this in core.css:

```
.social {
   -webkit-transition-duration: 0.4s;
   -moz-transition-duration: 0.4s;
   -o-transition-duration: 0.4s;
   transition-duration: 0.4s;
}

.social:hover {
    opacity: 0.65;
}
```

**Comment by benobab** [comment]
@hyperreality I've updated the code with your css and fixed the bug where you can't click the buttons at all (xs rather than md for bootstrap).

**Comment by lirantal** [comment]
Thanks a lot @benobab, I fixed the conflict and added to your commits a new PR which can be merged at: https://github.com/meanjs/mean/pull/1450

**Comment by lirantal** [comment]
closed through PR #1450

**Pull request closed without merging**
