### PR TITLE
Fix two issues:

### PR DESCRIPTION
**Pull request by AlexBoYang**
1. Visiting http://localhost:3000/abc/def (this path does not exist) will not display 404 page. That is because the css and javascript library path is relative directory not root directory of MEAN.
2. Do not remove the "removeRoot" string ("public/" in MEAN source code) only if it is at the beginning of the path

### CODE REVIEW

**Comment by lirantal** [comment]
@AlexBoYang I tested on Linux and it looks ok.

**Comment by ilanbiala** [comment]
@NeverOddOrEven does this conflict/overlap with the image path PR?

**Comment by lirantal** [comment]
@AlexBoYang looks like this is till happening on 0.4.0, would you like to send a PR to fix it?

**Comment by ilanbiala** [comment]
@AlexBoYang @lirantal is this still a problem?

**Comment by AlexBoYang** [comment]
Let me check.

**Comment by AlexBoYang** [comment]
Those issues have been solved in current master branch.

**Pull request closed without merging**
