### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ilanbiala**
WIP

### CODE REVIEW

**Comment by ilanbiala** [comment]
@codydaig @lirantal @mleanos @rhutchison looks like this one should be good. I'll update some of the devDeps in a separate commit on this PR once I finalize the regular dependencies. There were some Socket.io issues, so I didn't update Phantom.js or Socket.io.

**Comment by mleanos** [comment]
@ilanbiala What are the different builds that were run here?

Also, what is the difference between *travis-ci/pr* & *travis-ci/push*? It looks like the */push* one is new, but it passes :)

**Comment by rhutchison** [comment]
Duplicates #1198

**Comment by ilanbiala** [comment]
pr and push run the same ones, I just cancelled pr so more builds on push could run. CircleCI I don't even think is connected, I'm not sure why it shows up and same with Codeship.

**Comment by ilanbiala** [comment]
@rhutchison too many changes in one PR, we're trying to keep everything focused on one thing only.

**Comment by ilanbiala** [comment]
@mleanos @lirantal @codydaig LGTY? CircleCI and Codeship don't run tests, so those can be ignored.

**Comment by mleanos** [comment]
I pulled this down, and ran into an issue with gulp-protractor. I couldn't run `gulp test:e2e`, as it threw an error either during install, or after installing, the webdriver. (I didn't take note of that).

Our builds aren't using Gulp yet, so I'm wondering if we should hold off on updating the version of `gulp-protractor` at this time. After we move over to Gulp completely, then we can work on getting Protractor upgraded. WDYT?

Other than that, everything looks good, and everything was functioning properly after applying all these upgrades.

**Comment by mleanos** [comment]
This is the error I get after upgrading `gulp-protractor` to `2.1.0`

gh-1213-gulp-protractor-2 1 0-error

**Comment by ilanbiala** [comment]
@mleanos rolled back to 2.0.0, if that doesn't fix it I'll roll back to the original 1.0.0 and we should be fine.

**Comment by ilanbiala** [comment]
@mleanos does it work for you now?

**Comment by ilanbiala** [comment]
@codydaig LGTY?

**Comment by mleanos** [comment]
Now I'm getting this error. It doesn't look like Protractor is installing correctly for me. I'm getting errors on the install. Sometimes I get errors when installing packages, and then just re-run the install & no errors are thrown. It probably has to do with me being on Windows & Node v0.12.7 ? 

gh-1213-gulp-protractor-2 0 0-error

I'm sure if I upgraded to Node 4, I wouldn't be having so many issues with packages. I'm hoping to avoid upgrading until we drop support for v0.12.7. Which should be soon, I guess.

**Comment by ilanbiala** [comment]
@mleanos reverted to original version, it should work now.

**Comment by mleanos** [comment]
I'm travelling the next few days so I can't test. However, that package was the only issue I had. 

So this is probably good to go.

**Comment by ilanbiala** [comment]
@codydaig LGTY?

**Comment by lirantal** [comment]
@ilanbiala I also had local problems as @mleanos mentioned with getting the protractor tests running so can you just make sure those are working ok on your end?

**Comment by ilanbiala** [comment]
@lirantal did you do `npm cache clean`/delete `node_modules` and do a fresh install? It worked for me.

**Comment by lirantal** [comment]
I get this:
```bash
Running "protractor:e2e" (protractor) task
webdriver-manager path: /meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager
selenium standalone is up to date.
chromedriver is up to date.
[launcher] Process exited with error code 1
/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Could not find chromedriver at /meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/chromedriver
    at LocalDriverProvider.addDefaultBinaryLocs_ (/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/lib/driverProviders/local.js:54:15)
    at LocalDriverProvider.setupEnv (/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/lib/driverProviders/local.js:71:8)
    at Runner.run (/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:261:31)
    at TaskRunner.run (/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/lib/taskRunner.js:123:19)
    at createNextTaskRunner (/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/lib/launcher.js:223:20)
    at /meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/lib/launcher.js:246:7
    at _fulfilled (/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:759:13)
    at /meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:573:44
>> /meanjs.git/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:126
>>                     throw e;

```

**Comment by ilanbiala** [comment]
@lirantal @mleanos any more issues, or LGTY? I want to get this merged in so we can finish off some of the other dep. updates PRs.

**Comment by mleanos** [comment]
I didn't have any issues with `gulp-protractor 1.0.0`, and I didn't have any other issues with this PR. I'm still travelling, but should be able to test this in the evening (PT).

**Comment by lirantal** [comment]
@ilanbiala go ahead and merge this PR, let's get them rolling!

**Comment by mleanos** [comment]
@ilanbiala @lirantal I initially had problems with one of the Karma dependencies after re-installing all packages after this was merged. I'm not sure which dependency was the issue. The client tests were failing.

However, today I ended up re-installing all the Karma dependencies, and everything is running great now. Must've been a dependency issue either locally, or a patch that was released.

@lirantal Did you have any problems, after this merge?

**Comment by lirantal** [comment]
I'll check and report back if I have any issues.

**Pull request merged**
