### PR TITLE
Fix static files BEFORE sessions

### PR DESCRIPTION
**Pull request by pursual**
To avoid a mongo ping per static file. #1089

### CODE REVIEW

**Comment by mleanos** [comment]
@pursual Thank you for submitting this fix. The build failed due to a timeout. You can close & re-open this PR, to initialize the build process again. Hopefully, it was just an intermittent timeout.

**Comment by mleanos** [comment]
LGTM. 

Any other considerations? @codydaig @ilanbiala @lirantal

**Comment by mleanos** [comment]
@pursual Before this is merged, you will need to change the commit message to conform to the Contributing guidelines. This is for the commit history, and to easily track changes in release changelog's.

https://github.com/meanjs/mean/blob/master/CONTRIBUTING.md

**Comment by mleanos** [comment]
@pursual The actual commit message, not the body should contain the header. See these commits.. 
https://github.com/meanjs/mean/pull/1083/commits

**Comment by pursual** [comment]
I'm away for the weekend, feel free to close and recreate.

**Comment by ilanbiala** [comment]
Code LGTM, I don't there there are any issues with doing that.

**Comment by codydaig** [comment]
Squash the commits and then LGTM

**Comment by pursual** [comment]
Sorry, I give up, you guys have the info needed.

**Comment by pursual** [comment]
Closed and resubmitted.

**Pull request closed without merging**
