### PR TITLE
cleaning up application startup information

### PR DESCRIPTION
**Pull request by lirantal**
On starting up the server:
1. Remove the 'application started' suffix to the application title
2. Align the database name tab length
3. Remove the initial 'Application loaded using <NODENEV> environment' as it is anyway reported in the startup info.

Startup information after the fix:
image

### CODE REVIEW

**Comment by danaronoff** [comment]
Is mean-test now the DB for the dev environment? I noticed that changed during the merge. It used to be mean-dev.

**Comment by lirantal** [comment]
you're right, I submitted another PR for that: https://github.com/meanjs/mean/pull/641

**Comment by lirantal** [comment]
I guess we can merge that?

**Comment by ilanbiala** [comment]
Yep, looks good.

**Pull request merged**
