### PR TITLE
Auth service

### PR DESCRIPTION
**Pull request by sylvainlap**
Added the $window, no need of _this.

### CODE REVIEW

**Comment by ilanbiala** [comment]
I like this change a lot. @lirantal any issues with it? Tests are still passing.

**Comment by sylvainlap** [comment]
@ilanbiala Glad you like my change ;)

**Comment by ilanbiala** [comment]
@lirantal LGTY?

**Comment by lirantal** [comment]
@ilanbiala if it works for you, I'm not experienced with Angular.

**Pull request merged**
