### PR TITLE
Replacing deprecated gulp node inspector

### PR DESCRIPTION
**Pull request by lirantal**
The dependency `gulp-node-inspector` is deprecated.
This PR introduces a replacement setup with the vanilla `node-inspector` package and updates the Dockerfile as well.

### CODE REVIEW

**Comment by lirantal** [comment]
Is it this PR or something badly broken with npm / build process?

**Comment by lirantal** [comment]
cc @meanjs/contributors, @meanjs/core

**Comment by simison** [comment]
@lirantal seems to be this: https://github.com/sindresorhus/gulp-imagemin/issues/221

**Comment by lirantal** [comment]
Indeed.

**Comment by lirantal** [comment]
@meanjs/contributors what say you?

**Comment by mleanos** [comment]
@lirantal I haven't tested, but it looks correct to me.

I say merge, since the builds are passing. 👍

**Comment by lirantal** [comment]
Great.

**Pull request merged**
