### PR TITLE
RAML checker

### PR DESCRIPTION
**Pull request by sielay**
This change introduce first stage of integration with RAML to document and validate API.

 * adds task `gulp raml` that will check Express routes definitions against RAML and other way around
 * I left two invalid RAML rules to show you output

In further steps we can introduce tests with [Abao](https://github.com/cybertk/abao/)

Benefits:
 * Keeps you with up to date API documentation and tells you that you need to update it
 * RAML allow you to generate quite powerful docs and testing consoles (it's far more mature than Swagger)
 * Allows you to use testing like Abao which can run schema validation against responses

`Note`: I use tabs as expected. Anyhow my dumb InteliJ don't allow tabs in YAML files. Maybe there is reason for it.

### CODE REVIEW

**Comment by lirantal** [comment]
Hi @sielay 
What's RAML and why do we need it? what does this PR affect except for adding some documented API and updating gulp to support it?

**Comment by sielay** [comment]
@lirantal RAML is most used standard to document RAML apis. For my projects it allows to introduce tools like Abao to gain close to 100% server side code coverage in tests.

**Comment by codydaig** [comment]
IMO, it seems to fit a specific type of implementation and just adds another layer of "documentation" that would need to be supported.

**Comment by codydaig** [comment]
There was also an initial discussion on this in #352

**Comment by lirantal** [comment]
@sielay I'm ok with looking into this but let's do that as part of 0.5.0 which will take more focus on documentation, testing, etc.

**Pull request closed without merging**
