### PR TITLE
move helmet and express.static before sessions for performance

### LINKED ISSUE #318: Move static files middleware before sessions
I was having a performance problem with reloading a site built off of meanjs.  I solved the problem by moving the config for the static files middleware before the sessions middleware.  Static files load significantly faster because there isn't session tracking being done for each of them.

### PR DESCRIPTION
**Pull request by bmonty**
See issue #318 for details on changes.  Closes #318.

### CODE REVIEW

**Comment by lirantal** [comment]
there's some information on the performance improvement on the original ticket filed: https://github.com/meanjs/mean/issues/318

**Comment by ilanbiala** [comment]
@lirantal this looks good to merge, no?

**Comment by lirantal** [comment]
I'll merge it after I'll be able to test it a little, and I can't test now because https://github.com/meanjs/mean/issues/334#issuecomment-68789893 seems like a critical bug now that is a show-stopper for meanjs 'master' branch and we need to fix it first

**Comment by lirantal** [comment]
@ilanbiala was finally able to test it and confirm nothing has broken and looks pretty ok to me.
I'll go ahead and merge.

**Pull request merged**
