### PR TITLE
Use validator.js instead of regexp for validations in User Schema.

### PR DESCRIPTION
**Pull request by fauria**
The original regexp did not filter some invalid email addresses, such as "foo..bar@example.com". Replaced with [validator.js](https://github.com/chriso/validator.js)

### CODE REVIEW

**Comment by lirantal** [comment]
@fauria I like this.
Can you submit another PR for 0.4.0 branch instead of this one?

**Comment by fauria** [comment]
Sure, no problem!

**Comment by fauria** [comment]
Sure! Just submitted, see: https://github.com/meanjs/mean/pull/656

**Comment by lirantal** [comment]
Great, I merged it, thank you.

**Pull request closed without merging**
