### PR TITLE
[fix] Empty Chat Messages

### PR DESCRIPTION
**Pull request by mleanos**
This is something that has been bothering me for a while...

Disables the submit button on the Chat form, when no message is present.
Also, removed the `data-` prefix from the various Chat view elements.

### CODE REVIEW

**Comment by codydaig** [comment]
LGTM

**Comment by lirantal** [comment]
Thanks guys

**Comment by mleanos** [comment]
@lirantal No problem. Thanks for merging. It's the baby-commits.. kind of like *baby steps* :)

**Comment by lirantal** [comment]
Baby commits are easier to code review so I'm always up for them :)

**Pull request merged**
