### PR TITLE
Update package.json: devDependencies

### PR DESCRIPTION
**Pull request by shayas**
Update karma version to 0.13.10

### CODE REVIEW

**Comment by ilanbiala** [comment]
Breaking Changes

The public api interface has changed to a constructor form. To upgrade change javascript var server = require(‘karma’).server server.start(config, done)  to javascript var Server = require(‘karma’).Server var server = new Server(config, done) server.start()  Closes #1037, #1482, #1467 (82cbbadd)

@jloveland we may need to use this in Gulp to make sure the server is running before Karma is.

**Comment by mleanos** [comment]
@ilanbiala Can you explain what the issue is here? Why do we need to update to this newer version of Karma?

I've been doing some work with Karma & Gulp, so I'm just trying to understand. 

Also, we have this open PR #891

**Comment by ilanbiala** [comment]
@mleanos just some bug fixes and deps updates.

**Comment by mleanos** [comment]
@ilanbiala Thank you. I'll look into that, and test this newer version.

**Comment by ilanbiala** [comment]
@mleanos did you ever run into any problems with the new version of karma? I don't think I had any issues, but it was a long time and I may have forgotten something.

**Comment by ilanbiala** [comment]
@shayas can you also upgrade grunt-karma to 0.12.1 and remove gulp-karma and switch the implementation to the one found in https://github.com/karma-runner/gulp-karma?

**Comment by ilanbiala** [comment]
Superseded by #1080.

**Comment by mleanos** [comment]
@ilanbiala Thank you. And to answer your question about Karma. I didn't run into any problems.

**Pull request closed without merging**
