### PR TITLE
snyk support in CI/CD

### PR DESCRIPTION
**Pull request by lirantal**
Adding snyk support to test our dependencies for insecure vulnerabilities as part of our build process

### CODE REVIEW

**Comment by trendzetter** [comment]
pretty cool idea!

**Comment by simison** [comment]
Snyk is nice.

This one is crusial, in their September email:
>**Changes to how Snyk runs tests on pull requests**
>
>We are rolling out improvements to our GitHub integration. As a first step, we have added settings for how Snyk runs tests on pull requests (for repos that you are watching with Snyk).
>
>What we have changed
>
>Currently, Snyk Test on a PR fails if the repo has any vulnerabilities. 
>
>We are changing this:
>
>- By default, Snyk Test will only fail if the PR is introducing vulnerabilities. 
>- You can configure Snyk Test to fail if the repo has any vulnerabilities. 
>- You can now choose to only fail tests for high severity vulnerabilities.

**Comment by lirantal** [comment]
Yep. Let's stabalize the branch first with the old dependencies we have and then integrate it fully.

**Comment by sujeethk** [comment]
Is it possible to rerun the travis build on this commit? When i run snyk manually on latest master it shows no vulnerabilities. If that clears the checks, it would be good to get this into 0.5.0. 
cc @mleanos

**Comment by sujeethk** [comment]
[Known Vulnerabilities](https://snyk.io/test/github/meanjs/mean/ef3b361c09c6b07ffb10f4e345638851ba232ea3)

**Pull request merged**
