### PR TITLE
bug(readme): Remove Broken Live Demo Link

### PR DESCRIPTION
**Pull request by codydaig**
The link to the live demo in the README is broken. 

Credit @marqshort for discovering it.

### CODE REVIEW

**Comment by ilanbiala** [comment]
I'd rather not remove it, but fix it. I get this error:

```
Server Error

	MongoError: not authorized for query on meanjs.sessions
    at Object.toError (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:685:54
    at Cursor.close (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:959:5)
    at commandHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:685:21)
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1806:9
    at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
    at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
    at emit (events.js:95:17)
```

**Comment by codydaig** [comment]
@ilanbiala Who has access to the heroku app? It hasn't even been updated since the release of 0.4

**Comment by ilanbiala** [comment]
@codydaig what would be awesome is if we just set up a server that pulls the master branch and runs grunt and serves the app, no? Not sure Heroku's the best for that, I don't know if there is any way we can get a VPS of some sort that will let us set up something like that or maybe get credit on AWS from Amazon as an open source project, because I think they have support for this.

**Comment by palpalani** [comment]
Team, I am using [CodeShip](https://codeship.com) for automatic deployment from github to heroku. Their basic plan is free and supports 100 builds for month.

Just for information, For dependency updates other open source projects are using [GreenKeeper](http://greenkeeper.io/). Which creates automatic pull request when dependency get updates.

We have application which developed year before using [meanjs](http://meanjs.org/) deployed in heroku. Recently found minor bug and we fixed. when we updating system we received lot issues with dependencies. Because we are using ~ and ^ symbols in package.json. If we use [npm-shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) then this problem will be solved. Personally, we feel that, Meanjs should recommend to use this tool.

**Comment by codydaig** [comment]
@palpalani The discussion about the dependencies should be brought up in a new issue. It's not relevant to this PR. 

@palpalani Thanks for the tip about CodeShip, I'll look into it!

@ilanbiala I have a server cluster set-up that handles automatic updates and deployment. I can easily add meanjs too it if that's of interest. All it takes is a web hook to my server and a couple minutes of configuration and it's ready to go.

**Comment by lirantal** [comment]
@ilanbiala  I like the idea of having a server up that is synced with `master` after every build that serves as a demo.
I do however think we should merge this PR now because that link is broken and we don't know what's the ETA for @ilanbiala 's proposal so we better not be embarrassed with broken links in our framework in the meanwhile.

**Comment by codydaig** [comment]
@ilanbiala I'll open an issue for the deployment to continue discussions.

**Comment by ilanbiala** [comment]
:+1:

**Pull request merged**
