### PR TITLE
Formatting fixes for ESLint

### PR DESCRIPTION
**Pull request by ilanbiala**
This has all the formatting changes and ESLint support (temporarily so we can confirm it passes in Travis).

### CODE REVIEW

**Comment by ilanbiala** [comment]
@lirantal @mleanos @codydaig once you guys give me the word, I'll remove ESLint support from this and merge it and then we can go back to #990 for actual ESLint support.

**Comment by codydaig** [comment]
LGTM. 

Also, I'm cool with combining the PRs and just squashing down to two commits (one for the eslint addition, and one for the formatting changes).

**Comment by mleanos** [comment]
I'm also fine with two commits in one PR. 

I'd like to take this for a quick test run, and review.   I should be able to complete that in an hour or so.

**Comment by mleanos** [comment]
LGTM. Thanks @ilanbiala

**Comment by mleanos** [comment]
@ilanbiala Upon looking at this again, I realized the Gulp task is failing.. It throws an error at this line
https://github.com/meanjs/mean/pull/991/files#diff-b9e12334e9eafd8341a6107dd98510c9R112

```
4:58] Starting 'eslint'...
4:58] 'eslint' errored after 478 ms
4:58] TypeError: undefined is not a function
```

**Comment by ilanbiala** [comment]
@mleanos I'm thinking it stems from this line because we don't pass in a formatter and when it tries to write it can't execute the function because it's undefined https://github.com/adametry/gulp-eslint/blob/master/util.js#L180. Can you paste in the stack trace if there is one?

**Comment by ilanbiala** [comment]
I'm going to do them as 2 separate PRs because I already have it set up like that locally. @mleanos try adding `.eslint` in between `plugins.format()` because the plugin is eslint and the method is format. Once you confirm, I'll merge this and then the actual ESLint setup in the other PR.

**Comment by mleanos** [comment]
@ilanbiala adding ".eslint" to that line fixed the Gulp issues..

This LGTM now! Thank you :)

**Comment by lirantal** [comment]
I missed the party but good thing to see this already fixed and joined in with the eslint file!
Great job @ilanbiala

**Pull request merged**
