### PR TITLE
Initial Support For Deploying To Cloud Foundry

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Cloud Foundry is a popular open source platform-as-a-service.  The MEANJS starter project is a great starting point for developers looking to get started with the MEAN stack.  This pull request would make it easy to get the MEANJS app deployed to any Cloud Foundry PaaS.  This pull request is for the code portion only, there also needs to be some documentation on how someone would deploy the MEANJS app to Cloud Foundry.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@ryanjbaxter take a look at https://github.com/meanjs/generator-meanjs structure, and it would probably make sense to add a separate folder for deployments. @NeverOddOrEven may be able to help bring this in.

**Comment by NeverOddOrEven** [comment]
@ryanjbaxter @ilanbiala I will be addressing the deployment workflows with the generator. Once those are aligned, will likely merge this to 0.4

**Comment by ryanjbaxter** [comment]
Cool let me know if you need some help!

**Comment by ilanbiala** [comment]
@NeverOddOrEven should we close this and continue any conversations in the generator repo?

**Comment by lirantal** [comment]
@ryanjbaxter this looks like a good PR addition, can you wrap it up for 0.4.0?

@ilanbiala while @roieki voted for moving this to the generator as well as moving out any docker/other deployment method it doesn't seem likely that 0.4.0 generator will be updated anytime soon and it's ok to have it on master/0.4.0 code than nowhere else. WDYT?

**Comment by ilanbiala** [comment]
@lirantal Sounds good to me.

**Comment by ryanjbaxter** [comment]
@lirantal let me take a look at this again next week

**Comment by lirantal** [comment]
Great, thanks guys.
So @ryanjbaxter I'll be closing this one because it's for master and we need a PR for 0.4.0, once you submit it I'll merge.

**Comment by ryanjbaxter** [comment]
@lirantal see #681 for 0.4.0 pull request

**Pull request closed without merging**
