### PR TITLE
removed /#! in user controllers

### PR DESCRIPTION
**Pull request by ycmjason**
Well in 0.4.0 obviously we dont want /#!/ :dancer:

### CODE REVIEW

**Comment by ilanbiala** [comment]
LGTM, but are there any other places that need to be fixed? What about SEO? Does this affect that at all?

**Comment by lirantal** [comment]
@ycmjason looks ok, can you fix your PR?

**Comment by rhutchison** [comment]
imho, this should not be merged.  This will break routes when html5mode is disabled or not supported.

**Comment by lirantal** [comment]
@rhutchison but if that were the case then wouldn't we need to add the #! everywhere else on other URLs?

**Comment by ilanbiala** [comment]
@rhutchison I'm not sure why someone would disable html5mode and most browsers support it today anyway.

**Comment by rhutchison** [comment]
@ilanbiala I'm not sure why someone would disable it, but I am identifying it as a concern.

@lirantal in most cases, our href's are generated through ui-sref which considers pushState support and the html5mode flag.

Since this is a change on the server-side, and there are no good methods to detect browser capabilities, it's best to leave as-is, unless we decide to drop support for unsupported browser (http://caniuse.com/#feat=history).

**Comment by ilanbiala** [comment]
I don't mind dropping IE8 and IE9, anyway Angular 1.5/2.0 is probably going to drop support there..

**Comment by lirantal** [comment]
you won't hear me complaining about IE9 :-)
if this cleans stuff up then I'm forward with this because those messy URLs look awful in code and doesn't look like they are supposed to be there.

unless this is truly breaking something I'm ok with this PR.

**Comment by rhutchison** [comment]
I am ok with dropping support for IE9, but I think we should update documentation to note that we only support [evergreen browsers](http://eisenbergeffect.bluespire.com/evergreen-browsers/).

**Comment by ilanbiala** [comment]
@rhutchison I don't think we need to do just Evergeen, but I would say IE10+ and latest of Safari.

**Comment by codydaig** [comment]
The percentage of IE users are slowly dropping. I think it's reasonable to say IE10+.

**Comment by lirantal** [comment]
So if we're ok with cleaning up the URLs then I've got the updated PR for it: https://github.com/meanjs/mean/pull/693

**Pull request closed without merging**
