### PR TITLE
Note for users that they may need to use sudo for installing the pack

### PR DESCRIPTION
**Pull request by SibuStephen**
Users note (For one using linux ), this note will provide an overview that sudo might be required for installing some of the packages as such.

### CODE REVIEW

**Comment by simison** [comment]
BTW, NodeJS download URL is wrong, should probably be this instead: https://nodejs.org/en/download/

**Comment by SibuStephen** [comment]
@simison  Please review, the changes as per saying.

**Comment by lirantal** [comment]
No packages should be installed as sudo, we already discussed it.
See https://github.com/meanjs/mean/pull/309 and https://github.com/meanjs/mean/pull/350

**Comment by SibuStephen** [comment]
@lirantal , Yes got it.

**Pull request closed without merging**
