### PR TITLE
test it 

### PR DESCRIPTION
**Pull request by sergiregi88**
It is a test you must don't accept it

### CODE REVIEW

**Comment by lirantal** [comment]
@sergiregi88 ?

**Comment by SOSANA** [comment]
@lirantal shouldn't this be broken up into individual PR's?

**Comment by ilanbiala** [comment]
This looks like a conglomeration of commits that have been made on master or 0.4.0 because I've seen most of these changes in commits and PRs before.

**Comment by lirantal** [comment]
this overall looks like a mistaken, so unless @sergiregi88 can comment what's this about we can ignore for now.

**Pull request closed without merging**
