### PR TITLE
Adding protractor options to fix travis failing

### PR DESCRIPTION
**Pull request by jloveland**
This is WIP for #961

### CODE REVIEW

**Comment by jloveland** [comment]
I think we should try to use Sauce Labs:
http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-Sauce-Labs

**Comment by lirantal** [comment]
@jloveland why are you opening/closing this? to re-run the CI?

**Comment by jloveland** [comment]
@lirantal yes, this PR was a WIP that didn't work out. I submitted a new PR #968 to address issue #961

**Comment by lirantal** [comment]
Got it.

**Pull request closed without merging**
