### PR TITLE
Fixing Menus service removeMenuItem and removeSubMenuItem

### LINKED ISSUE #777: Menus service bug in removeSubMenuItem and removeMenuItem
The following methods in the Menus service are currently buggy..

[_removeMenuItem_](https://github.com/meanjs/mean/blob/master/modules/core/client/services/menus.client.service.js#L146)
[_removeSubMenuItem_](https://github.com/meanjs/mean/blob/master/modules/core/client/services/menus.client.service.js#L163)

__Can reproduce with:__
```javascript
   it('should remove menu item', function() {
      Menus.addMenu('menuId');
      Menus.addMenuItem('menuId', {state:'menu.state'});
      var menu = Menus.removeMenuItem('menuId', 'menu.state');
      expect(menu.items.length).toBe(0);
    });
```

__Cause:__
Both methods attempt to remove a menu item that has a _link property_ (that we no longer use after 0.4.0) that matches the URL passed into the method.

### PR DESCRIPTION
**Pull request by cdriscol**
Fixing Menus service removeMenuItem and removeSubMenuItem by.. 

* modified tests to reproduce issues
* replaced references to old link property with new state property

Fixes #777

### CODE REVIEW

**Comment by mleanos** [comment]
LGTM. Verified that the new tests are passing. 

Thanks @cdriscol these tests are looking very nice.

**Comment by codydaig** [comment]
LGTM

**Comment by codydaig** [comment]
@cdriscol This PR has a merge conflict that needs to get resolved before it can be merged.

**Comment by cdriscol** [comment]
Replaced by #810

**Pull request closed without merging**
