### PR TITLE
User ID middleware now uses .findById

### PR DESCRIPTION
**Pull request by ilanbiala**
Better use of syntactic sugar.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@lirantal @NeverOddOrEven simple change, let me know if I can merge.

**Comment by ilanbiala** [comment]
@lirantal This is the only instance I found by the way, so this will make it more consistent and cleaner.

**Comment by lirantal** [comment]
why are we replacing findById() with findOne() ?

**Comment by ilanbiala** [comment]
Because it's in ID middleware, and findById is cleaner, more readable, and suited for this function.

**Comment by lirantal** [comment]
It's internal to mongoose, and is just a wrapper for findOne anyway... I'm ok with the PR overall, don't have anything against.

**Comment by ilanbiala** [comment]
It is a wrapper, but it's a useful one that makes it much easier to understand what the main purpose is at a glance.

**Pull request merged**
