### PR TITLE
Server Side Test Coverage

### PR DESCRIPTION
**Pull request by MangeshPimpalkar**

### CODE REVIEW

**Comment by sielay** [comment]
It seem to work, but in fact it runs only server.js and ends. In report you see nothing really and it fails on trying to load first mongoose model.

**Comment by ilanbiala** [comment]
@MangeshMp the indentation and all that has to be changed back and the PR has to be rebased.

**Comment by lirantal** [comment]
@MangeshMp looks like a great addition, would you like to re-submit this PR by cleaning up the indentation and solving whatever conflicts there are?

**Comment by ilanbiala** [comment]
@MangeshPimpalkar can you tidy this up in a new PR?

**Comment by ilanbiala** [comment]
@lirantal judging by when this PR was created, I'm guessing it's quite a bit out of date. I think we should just add tests as we go instead of holding off on 0.4.0 for this when it's going to require lots of changes.

**Comment by lirantal** [comment]
@ilanbiala I have a local branch to work on this issue exactly, it's not very simple and will need a refactor to the main server.js file, maybe I'll be able to push something in later today for you to review.

**Comment by lirantal** [comment]
Thanks @MangeshPimpalkar!
I've implemented the same at #811 please go and review

**Pull request closed without merging**
