### PR TITLE
removed ng-init from views, split controller, modified karma tests to reflect the changes

### PR DESCRIPTION
**Pull request by androidfred**
This is my suggested refactor for this issue https://github.com/meanjs/mean/issues/325

### CODE REVIEW

**Comment by codydaig** [comment]
Is this something that we want implemented in 0.4.0?
IMO, its a case by case basis and I think the for boiler plate, the controllers should be left in a single file.

**Comment by lirantal** [comment]
@androidfred this indeed isn't going to master neither to core 0.4.0
maybe you want to reach out to @rhutchison on gitter chat to discuss more improvements to the UI.

**Comment by androidfred** [comment]
Thanks for your attention.

As Angular docs say you should use controllers rather than ngInit to initialize values on a scope, and that a controller should contain only the business logic needed for a single view, I hope both these issues are addressed by some other means.

**Comment by lirantal** [comment]
once we release 0.4.0 we can discuss about these kind of changes and you're welcome to offer a PR then.

**Pull request closed without merging**
