### PR TITLE
Added uploads folder under module/users/client/img/profile so that us…

### PR DESCRIPTION
**Pull request by ycmjason**
…ers can upload photos properly.
Couldn't find a way to just add the folder so.. uhh...

### CODE REVIEW

**Comment by simison** [comment]
Hmm, this should be either at Grunt task or at the controller with [mkdirp](https://www.npmjs.com/package/mkdirp).

**Comment by ycmjason** [comment]
You might be right, forgive my ignorant. I am just a newbie.

**Comment by simison** [comment]
No worries man. :-) Good you pointed this out!

**Comment by ycmjason** [comment]
Another question, is there any complete/incomplete documentation for this version yet?

**Comment by ilanbiala** [comment]
@ycmjason most of the documentation for 0.4.0 still needs to be written and tidied up. We're finishing up some loose ends in the code (take a look at the milestone specifically) and then we'll fix all the docs.

**Comment by mleanos** [comment]
I'm having an issue with this directory, when deploying to Heroku. During deployment, Heroku will destroy this uploads directory. Adding it to .gitignore won't help this issue. 

Has anyone had any success when deploying to Heroku? Or any advice, perhaps?

**Comment by lirantal** [comment]
@ycmjason would you like to fix this PR to instead of adding a file modify the grunt task to create this folder?

**Comment by codydaig** [comment]
Something we do internally for this is to add an empty file ".gitkeep" to note that this directory needs to exist.(#730 as an example)

**Comment by lirantal** [comment]
@codydaig I think we should update grunt to create this folder and not put it as part of the repository.

**Comment by codydaig** [comment]
@lirantal That's fine, just threw that out there as a suggestion. I closed my pull request.

**Comment by ilanbiala** [comment]
@ycmjason would you be able to create a grunt task like @lirantal suggested?

**Comment by simison** [comment]
@ilanbiala Check https://github.com/meanjs/mean/pull/731 — sorry, just Grunt task for now. I'm not sure if I'll have time to turn that for Gulp very soon (maybe in ~24h).

**Comment by lirantal** [comment]
@simison honestly the Gulp work isn't that interesting for the moment since it's not yet complete and we didn't officially transfer to Gulp so that would be good if you can send a PR for but it's definitely not urgent so can wait for post the 0.4.0 release.

**Comment by simison** [comment]
Aight! I'll look into it some time later when I'm back from travels, then.

This one could be closed.

**Comment by lirantal** [comment]
right, thanks

**Pull request closed without merging**
