### PR TITLE
return a 404 for not found api, module and lib routes

### LINKED ISSUE #501: Page not found handler not working in 0.4.0
Steps to reproduce:
* clone the repository;
* run `npm install`;
* run `grunt`;
* load an URL for which there's no route, e.g. http://localhost:3000/abcdefghijklmnopqrstuvwxyz (why not ;) )

Expected result:
* a 404 status code and a redirection to http://localhost:3000/not-found , displaying an error message.

Actual result:
* a 200 status code and a redirection to http://localhost:3000 , effectively displaying the root page.

If I remove the "*" from the last route of modules/core/server/routes/core.server.routes.js, the 404 functionality is restored; however, sign up, sign in and pretty much everything else is broken, because of the fallback to the error routes defined in config/lib/express.js. I haven't yet found what the correct fix is.

I noticed the issue on my own testing application, when the server not only produced a 200 status code, but also the HTML content of the root page, when requested an image which wasn't there.

### PR DESCRIPTION
**Pull request by dotch**
fixes #501

### CODE REVIEW

**Comment by ilanbiala** [comment]
So what routes have been modified now?

**Comment by dotch** [comment]
Sorry for the lacking explanation.

The server is responsible for the following routes:
`/api/*`
`/componens/*`
`/lib/*`
`/server-error`
The other routes (`/*`) are handled by Angular due to html5mode.

This PR shows the server 404 page for:
`/api/*`
`/componens/*`
`/lib/*`
when no route-handler kicks in due a non existing endpoint, component or library.

Angular route handling is not part of this PR.

**Comment by simison** [comment]
BTW, would be great if non existing API routes would return 404 as a JSON.

Something like this http://stackoverflow.com/a/9802006

**Comment by lirantal** [comment]
sounds like a good enhancement indeed, need to take a look at that further

**Comment by simison** [comment]
@lirantal are you gonna look into 404 stuff for 0.4.0? (har har those digits). If not, I'm also fiddling with this stuff now, but I'm sure you have more perspective.

This still requires 404 handling at Angular side, now app just redirects to `/` (often confusing users). Redirecting to `/not-found` is kinda fine, but would be better not to change URL at the URL-bar. `location:false` option at [$state.go()](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state#methods_go) could be useful for that.

Would be lovely to get real 404 headers working for `/*` stuff as well from Express (instead of giving the job for Angular), but that would require shared configs for URL routing between Express and Angular. Not sure how feasible is that...

**Comment by lirantal** [comment]
@simison go ahead and look at it, it's ok with me.

**Comment by simison** [comment]
@lirantal See https://github.com/meanjs/mean/pull/566

**Pull request merged**
