### PR TITLE
Ignore ALL .log files at gitignore

### PR DESCRIPTION
**Pull request by simison**
Smart practise. 

E.g. when app is served with Phusion Passenger or some other app server, you might end up having some log files at the root folder.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@lirantal no issues with this, right?

**Comment by lirantal** [comment]
yeah that's cool.

**Comment by ilanbiala** [comment]
@simison can you rebase and then I'll merge?

**Comment by ilanbiala** [comment]
@simison any issues rebasing?

**Comment by simison** [comment]
Sorry man, postponed this earlier with no time and then just forgot about this.

I'm no git ninja, did that now went as it shoulda?

**Comment by ilanbiala** [comment]
I think some things got copied from another commit, so I'm just going to commit it myself.

**Comment by simison** [comment]
:+1:

**Pull request closed without merging**
