### PR TITLE
0.4.0

### PR DESCRIPTION
**Pull request by flight-zorn**

### CODE REVIEW

**Comment by ilanbiala** [comment]
@flight-zorn thanks for initiating this. We are still working out a couple issues as seen in the milestone.

**Comment by lirantal** [comment]
Hey @flight-zorn, can you elaborate what is this PR for? it seems to be that you merged all of 0.4 branch into master. If so can you please elaborate. Where there any conflicts that you had to resolve, etc?

All in all, it's a blessed change that we've been trying to push forward to, let's see if we can get this mission completed.

**Comment by codydaig** [comment]
IMO, since there doesn't seem to be anything happening with the master branch and 0.3.3 I propose that we mark the current master branch as the 0.3.3 release so people can still download the 0.3.3 code and merge 0.4.0 into master. We can make the download link on the website download the latest release (0.3.3) while 0.4.0 gets wrapped up.

**Comment by lirantal** [comment]
I agree, though let's finish up with some 0.4.0 cleaning and then work out the release logistics.
I'll open an issue for reviewing this items are must for 0.4.0 before we seal it off.

Also, not sure what this PR is for so I'm closing.

**Pull request closed without merging**
