### PR TITLE
Supporting NodeJS v4 in Travis CI

### LINKED ISSUE #902: node 4.0 update
I have a error "Segmentation fault: 11" with server.js  when updated node to v4.0. 
How to fix it. 
thanks

### PR DESCRIPTION
**Pull request by lirantal**
Adding support for nodejs v4 and allowing it to fail without failing the complete build for CI.
Closes #902.

### CODE REVIEW

**Comment by lirantal** [comment]
is it possible this build is actually failing because it doesn't enforce the `matrix` directive there to allow failures because it's not in the `master` branch? I have some doubts because it had no problems identifying that we have a new build now for nodejs v4

**Comment by lirantal** [comment]
Ok, there we go. Now the build passes even though NodeJS v4 is failing. This way we can track it.
@ilanbiala  @codydaig let's continue with that to track v4 ready-ness?

**Comment by mleanos** [comment]
@lirantal Very well done.. Thank you! :+1:

**Comment by codydaig** [comment]
@lirantal LGTM! 
:-D Learn something new everyday.

**Comment by ilanbiala** [comment]
@lirantal did you see the warning about the legacy infrastructure on the [build log page](https://travis-ci.org/meanjs/mean/jobs/79970337)? Is there anything we use `sudo` for? If not, we might as well add `sudo: false` to the .travis.yml file as well. We would also be able to turn on [caching](http://docs.travis-ci.com/user/caching/).

```
cache:
  apt: true
  directories:
  - node_modules/
  - public/lib/
```

**Comment by ilanbiala** [comment]
@lirantal not sure if you saw, but I used the caching and new containerized setup for the generator and it speeds up builds pretty quickly. I think you should try it out before merging this in without it.

**Comment by lirantal** [comment]
@ilanbiala 
I saw it was failing but didn't yet review it fully.
Sure I'll make the changes with the caching too and we will take this for a spin, thanks!

**Comment by lirantal** [comment]
Looks like we are good now @ilanbiala

**Comment by ilanbiala** [comment]
@lirantal LGTM.

**Comment by codydaig** [comment]
LGTM

**Pull request merged**
