### PR TITLE
feat(build): Update dependencies

### LINKED ISSUE #1569: Discussion - package.json cleanup
**Discussion:**
The below dependencies are listed but not used

```
file-stream-rotator (1)
jasmine-core (0)
mocha (33)
phantomjs-prebuilt (102)
```

The below dev-dependencies are listed but not used

```
eslint (127)
eslint-config-airbnb (1)
gulp-node-inspector (282)
gulp-util (94)
istanbul (59)
lcov-result-merger (93)
node-inspector (235)
```

Also `connect-flash (0)` is being used in the express.js file but what is using this flash? I do not see it being used anywhere other than the middleware initialized.

The numbers in brackets are a node count of the total recursive dependencies for those modules.

Am I missing something. Or Is there a reason why they cant be removed?

### PR DESCRIPTION
**Pull request by simison**
Remove dependencies which are already installed via other dependencies:
- eslint (gulp-eslint)
- istanbul (gulp-eslint)
- mocha (gulp-mocha)

Remove unused dependency:
- gulp-util

Remove blackbox `eslint-config-airbnb`. Related #1846, #1674 — thoughts?

Move installing `lcov-result-merger` to Travis config since it's the only place where it's ever used.

Update a bunch of outdated dependencies.

Closes #1569

### CODE REVIEW

**Comment by lirantal** [comment]
if they're already installed through others then it's ok for now, we just need to keep an eye before they change it to peerDependencies and then we'll need to install them ourselves.

About airbnb I left a comment on #1846

**Comment by simison** [comment]
>if they're already installed through others then it's ok for now, we just need to keep an eye before they change it to peerDependencies and then we'll need to install them ourselves.

Yep; our Travis builds should fail at that point (unless `node_modules` is cached there). I tested installation with NPM 5.2.0

Actually I'll drop eslint-airbnb change off from this PR, it's a separate issue to work on.

**Comment by simison** [comment]
Done here.

BTW worth noting that I didn't update Mocha here yet, as it will require changes to test files as well.

**Comment by lirantal** [comment]
alright.

**Pull request merged**
